import type { Metadata, Viewport } from "next";
import "./globals.css";
import AuthGuard from "@/components/AuthGuard";
import Toaster from "@/components/Toaster";

// Viewport — kept separate from `metadata` per Next.js 14+ contract.
// `viewportFit: "cover"` is REQUIRED for `env(safe-area-inset-*)` to
// resolve to non-zero values on iPhone (notch + home indicator).
// `width: "device-width"` + `initialScale: 1` prevents the iOS
// "zoom-on-focus" anti-pattern for inputs sized < 16px.
// `themeColor` moved here from metadata (deprecated location).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#16a34a",
};

const SITE_URL = "https://mygananpro.com";
const SITE_TITLE = "גנן Pro — תפסיק לנהל לקוחות. תתחיל לנהל עסק.";
const SITE_DESCRIPTION =
  "ה-CRM הישראלי הראשון שנבנה ע״י גנן, בשביל גננים. לוח זמנים, פיננסים, הצעות מחיר ב-WhatsApp — באפליקציה אחת בעברית.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "גנן Pro",
  },
  // Branded link preview when /landing is shared on WhatsApp / Facebook /
  // Telegram. The actual image is generated by app/opengraph-image.tsx.
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: "גנן Pro",
    locale: "he_IL",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full bg-slate-50">
        <AuthGuard>{children}</AuthGuard>
        <Toaster />
      </body>
    </html>
  );
}
