export type SunLevel = 'full' | 'partial' | 'shade';
export type WaterLevel = 'low' | 'medium' | 'high';

export interface Plant {
  id: number;
  nameHe: string;
  nameLatin: string;
  categories: string[];
  sun: SunLevel;
  water: WaterLevel;
  description: string;
  height?: string;
  bloomSeason?: string;
  tips?: string;
}

export const PLANT_CATEGORIES = [
  { key: "all", label: "הכל", emoji: "🌿" },
  { key: "fruit-trees", label: "עצי פרי", emoji: "🍎" },
  { key: "citrus", label: "הדרים", emoji: "🍊" },
  { key: "ornamental-trees", label: "עצי נוי", emoji: "🌳" },
  { key: "trees", label: "עצים", emoji: "🌲" },
  { key: "shrubs", label: "שיחים", emoji: "🌿" },
  { key: "privacy-shrubs", label: "שיחי הסתרה", emoji: "🏡" },
  { key: "perennials", label: "רב שנתיים", emoji: "🌸" },
  { key: "annuals", label: "עונתיים", emoji: "🌻" },
  { key: "indoor", label: "צמחיה לבית", emoji: "🪴" },
  { key: "succulents", label: "סוקולנטים", emoji: "🌵" },
  { key: "cacti", label: "קקטוסים", emoji: "🌵" },
  { key: "trailing", label: "צמחיה נשפכת", emoji: "🍃" },
  { key: "shade", label: "צמחייה לצל", emoji: "🌑" },
  { key: "geophytes", label: "גיאופיטים", emoji: "🌷" },
  { key: "herbs", label: "עשבי תיבול", emoji: "🌱" },
  { key: "climbers", label: "מטפסים", emoji: "🌿" },
  { key: "winter-annuals", label: "עונתיים חורף", emoji: "❄️" },
  { key: "summer-annuals", label: "עונתיים קיץ", emoji: "☀️" },
  { key: "palms", label: "דקלים", emoji: "🌴" },
  { key: "hedge-trees", label: "עצי גדר חיה", emoji: "🌳" },
  { key: "roses", label: "ורדים", emoji: "🌹" },
  { key: "myrtles", label: "הדסים", emoji: "🌿" },
  { key: "convolvulaceae", label: "קונוולריים", emoji: "🌸" },
  { key: "ornamental-grasses", label: "דגני נוי", emoji: "🌾" },
  { key: "mediterranean", label: "ים-תיכוניים", emoji: "🫒" },
  { key: "aquatic", label: "צמחי מים", emoji: "💧" },
  { key: "ferns", label: "שרכים", emoji: "🌿" },
  { key: "bulbs", label: "בצלים", emoji: "🌷" },
];

export function plantImageUrl(plant: Plant): string {
  const genus = plant.nameLatin.split(' ')[0].toLowerCase();
  return `https://source.unsplash.com/400x300/?${encodeURIComponent(genus)},plant&sig=${plant.id}`;
}

export const PLANTS: Plant[] = [
  // ---- עצי פרי ----
  {
    id: 1,
    nameHe: "תפוח",
    nameLatin: "Malus domestica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "אביב",
    description: "עץ פרי נשיר הנפוץ בגינות ישראל. מניב פירות בסתיו ודורש קרה חורפית.",
    tips: "גזום בסוף החורף לתפוקה מרבית.",
  },
  {
    id: 2,
    nameHe: "אגס",
    nameLatin: "Pyrus communis",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "4-7 מטר",
    bloomSeason: "אביב",
    description: "עץ פרי נשיר עם פרחים לבנים יפים באביב. מניב פירות מתוקים בסתיו.",
    tips: "השקה סדירה בקיץ חיונית להבשלת הפרי.",
  },
  {
    id: 3,
    nameHe: "שקד",
    nameLatin: "Prunus dulcis",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "3-8 מטר",
    bloomSeason: "ינואר-פברואר",
    description: "עץ פרי ים-תיכוני הפורח בחורף בפרחים לבנים-ורודים לפני הצצת העלים.",
    tips: "עמיד בצורת ואינו צורך השקיה רבה לאחר הביסוס.",
  },
  {
    id: 4,
    nameHe: "זית",
    nameLatin: "Olea europaea",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "3-10 מטר",
    bloomSeason: "אביב",
    description: "עץ ים-תיכוני עמיד בצורת ועץ פרי חשוב. אורך חיים של מאות שנים.",
    tips: "גזום בתחילת האביב לשמירת צורה ועידוד פריחה.",
  },
  {
    id: 5,
    nameHe: "תאנה",
    nameLatin: "Ficus carica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "קיץ",
    description: "עץ פרי ים-תיכוני עתיק עם עלים גדולים מאוצבעים. פרי מתוק בקיץ ובסתיו.",
    tips: "גזום את הענפים החלשים בחורף לחיזוק הפרי.",
  },
  {
    id: 6,
    nameHe: "רימון",
    nameLatin: "Punica granatum",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "שיח/עץ נוי ופרי. פרחים כתומים בולטים ופרי אדום עשיר בנוגדי חמצון.",
    tips: "עמיד מאוד לחום ולצורת, מתאים לגינה ים-תיכונית.",
  },
  {
    id: 7,
    nameHe: "אפרסק",
    nameLatin: "Prunus persica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    bloomSeason: "פברואר-מרץ",
    description: "עץ פרי נשיר עם פרחים ורודים יפהפיים. מניב פירות בקיץ.",
    tips: "דרושה קרה חורפית מספקת להבטחת יבול טוב.",
  },
  {
    id: 8,
    nameHe: "משמש",
    nameLatin: "Prunus armeniaca",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "3-6 מטר",
    bloomSeason: "ינואר-פברואר",
    description: "עץ פרי מוקדם הפורח בחורף. פרי כתום מתוק בתחילת הקיץ.",
    tips: "פורח מוקדם — הגן מפני כפור.",
  },
  {
    id: 9,
    nameHe: "שזיף",
    nameLatin: "Prunus domestica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "אביב",
    description: "עץ פרי נשיר עם פרי סגול-אדום עסיסי. פורח לבן באביב.",
    tips: "השקה סדירה בתקופת התפתחות הפרי חיונית.",
  },
  {
    id: 10,
    nameHe: "אבוקדו",
    nameLatin: "Persea americana",
    categories: ["fruit-trees"],
    sun: "full",
    water: "high",
    height: "5-10 מטר",
    bloomSeason: "חורף-אביב",
    description: "עץ טרופי בעל עלים ירוקים גדולים ופרי שמני. צריך הגנה מקרה.",
    tips: "הגן מפני קרה וריחות חזקים שעשויים לפגוע בעץ.",
  },
  {
    id: 11,
    nameHe: "מנגו",
    nameLatin: "Mangifera indica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "4-10 מטר",
    bloomSeason: "חורף",
    description: "עץ טרופי גדול עם עלים ארוכים ופרי מתוק. אוהב חום ולחות.",
    tips: "דורש קיץ חם ולח להבשלת פרי איכותי.",
  },
  {
    id: 12,
    nameHe: "ענבים",
    nameLatin: "Vitis vinifera",
    categories: ["fruit-trees", "climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 5-15 מטר",
    bloomSeason: "אביב",
    description: "גפן נשירה הנותנת פרי עסיסי ומגוון. מתאימה לפרגולות ולגידול על גדרות.",
    tips: "גיזום חורפי נמרץ חיוני לתפוקה גבוהה.",
  },
  {
    id: 13,
    nameHe: "תמר",
    nameLatin: "Phoenix dactylifera",
    categories: ["fruit-trees", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "10-25 מטר",
    bloomSeason: "אביב",
    description: "דקל אייקוני של המזרח התיכון. נותן פרי מתוק ומשמש כעץ נוי מרשים.",
    tips: "עמיד לחום ולצורת — אחד העצים הסבלניים ביותר.",
  },
  {
    id: 14,
    nameHe: "גויאבה",
    nameLatin: "Psidium guajava",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "קיץ",
    description: "עץ טרופי עם פרי בעל ניחוח ייחודי. עלים ירוקים כהים ופרי לבן/ורוד.",
    tips: "מתאים לאזורים חמים ועמיד למחלות.",
  },
  {
    id: 15,
    nameHe: "קיווי",
    nameLatin: "Actinidia deliciosa",
    categories: ["fruit-trees", "climbers"],
    sun: "partial",
    water: "high",
    height: "מטפס",
    bloomSeason: "אביב",
    description: "גפן נמרצת הנושאת פרי עשיר בוויטמין C. צריכה תמיכה ומבנה לטיפוס.",
    tips: "נדרשים זכר ונקבה לפרייה, ודרושה קרה חורפית.",
  },
  // ---- הדרים ----
  {
    id: 16,
    nameHe: "לימון",
    nameLatin: "Citrus limon",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "כל השנה",
    description: "הדר פורה ועמיד הנותן פרי כמעט כל השנה. פרחים ריחניים לבנים.",
    tips: "דשן בחנקן מספר פעמים בשנה לפריחה ופריה רצופה.",
  },
  {
    id: 17,
    nameHe: "תפוז",
    nameLatin: "Citrus sinensis",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    bloomSeason: "אביב",
    description: "הדר קלאסי עם פרחים ריחניים מאוד ופרי מתוק. עץ נוי ופרי כאחד.",
    tips: "הגן מפני קרה חזקה מתחת ל-3 מעלות.",
  },
  {
    id: 18,
    nameHe: "מנדרינה",
    nameLatin: "Citrus reticulata",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "אביב",
    description: "הדר קומפקטי עם פרי מתוק וקל לקילוף. עץ גינה אהוב למשפחות.",
    tips: "מתאים לגידול בעציץ גדול על מרפסת.",
  },
  {
    id: 19,
    nameHe: "אשכולית",
    nameLatin: "Citrus paradisi",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "אביב",
    description: "הדר גדול עם פרי מריר-מתוק ועשיר בוויטמין C. עץ גדול ורחב כתר.",
    tips: "צריך חום רב להבשלת פרי מתוק.",
  },
  {
    id: 20,
    nameHe: "ליים",
    nameLatin: "Citrus aurantiifolia",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "כל השנה",
    description: "הדר טרופי עם פרי ירוק חמצמץ. פורח כמעט כל השנה.",
    tips: "רגיש לקרה — שמור בסביבה מוגנת בחורף.",
  },
  {
    id: 21,
    nameHe: "פומלה",
    nameLatin: "Citrus maxima",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "4-8 מטר",
    bloomSeason: "אביב",
    description: "ההדר הגדול בעולם עם פרי ענקי מתוק ועסיסי. עץ נוי מרשים.",
    tips: "דרוש שטח גדול — עץ מרשים ובולט.",
  },
  {
    id: 22,
    nameHe: "קלמנטינה",
    nameLatin: "Citrus clementina",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "אביב",
    description: "כלאיים של מנדרינה ותפוז עם פרי מתוק ותכלתי. עץ גינה קומפקטי.",
    tips: "יבול מוקדם — מוכן לקטיף בנובמבר-דצמבר.",
  },
  {
    id: 23,
    nameHe: "לימונית",
    nameLatin: "Citrus hystrix",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "אביב",
    description: "הדר דקורטיבי בעל עלים כפולים ייחודיים. הפרי עשיר בארומה.",
    tips: "מתאים לגידול בעציץ ולבישול אסייתי.",
  },
  // ---- עצי נוי ----
  {
    id: 24,
    nameHe: "ג'קרנדה",
    nameLatin: "Jacaranda mimosifolia",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "8-15 מטר",
    bloomSeason: "אביב-קיץ",
    description: "עץ נוי מרהיב עם אשכולות פרחים סגולים. עץ ציון מרכזי ברחובות ישראל.",
    tips: "אינו אוהב קרה — שתול באזורים חמים.",
  },
  {
    id: 25,
    nameHe: "בוגנוויליה",
    nameLatin: "Bougainvillea spectabilis",
    categories: ["ornamental-trees", "shrubs", "climbers"],
    sun: "full",
    water: "low",
    height: "3-10 מטר",
    bloomSeason: "כל השנה",
    description: "שיח/מטפס מרהיב עם עלי מכסה צבעוניים (ורוד, כתום, לבן). פורח כמעט כל השנה.",
    tips: "פחות מים = יותר פרחים. גזום אחרי כל גל פריחה.",
  },
  {
    id: 26,
    nameHe: "קסיה",
    nameLatin: "Cassia spectabilis",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "5-10 מטר",
    bloomSeason: "סתיו-חורף",
    description: "עץ נוי עם אשכולות פרחים צהובים בולטים בחורף.",
    tips: "פורח בעת שרוב העצים ישנים — מעניק צבע לגינת החורף.",
  },
  {
    id: 27,
    nameHe: "טיפואנה",
    nameLatin: "Tipuana tipu",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "10-20 מטר",
    bloomSeason: "קיץ",
    description: "עץ נוי גדול עם פרחים צהובים-כתומים ועלים עדינים. נותן צל נרחב.",
    tips: "עץ גדל מהיר — תכנן שטח מספיק לגדילתו.",
  },
  {
    id: 28,
    nameHe: "פלמת מלכה",
    nameLatin: "Syagrus romanzoffiana",
    categories: ["ornamental-trees", "trees"],
    sun: "full",
    water: "medium",
    height: "8-15 מטר",
    bloomSeason: "קיץ",
    description: "דקל נוי מרשים עם כתר ירוק טבעי. מתאים לפינות גן ולשדרות.",
    tips: "צריך דשן מיוחד לדקלים לשמירה על עלים ירוקים.",
  },
  {
    id: 29,
    nameHe: "ואשינגטוניה",
    nameLatin: "Washingtonia robusta",
    categories: ["ornamental-trees", "trees"],
    sun: "full",
    water: "low",
    height: "15-25 מטר",
    bloomSeason: "קיץ",
    description: "דקל גבוה ורזה עם חצאית של עלים יבשים. נפוץ מאוד ברחובות ישראל.",
    tips: "עמיד מאוד — כמעט אינו דורש טיפול לאחר ביסוס.",
  },
  {
    id: 30,
    nameHe: "פיקוס בנגלנסיס",
    nameLatin: "Ficus benghalensis",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "15-25 מטר",
    bloomSeason: "קיץ",
    description: "עץ ענק עם שורשי אוויר יורדים. מעניק צל נרחב.",
    tips: "שורשים פולשניים — שתול רחוק ממבנים וצנרת.",
  },
  {
    id: 31,
    nameHe: "שיטה כחלחלה",
    nameLatin: "Acacia saligna",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "low",
    height: "3-8 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח/עץ קטן עם כדורים צהובים ריחניים בחורף. עמיד בצורת.",
    tips: "גדל מהיר ומתאים לגידור ולייצוב קרקע.",
  },
  {
    id: 32,
    nameHe: "אלבציה",
    nameLatin: "Albizia julibrissin",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "6-12 מטר",
    bloomSeason: "קיץ",
    description: "עץ נוי עם פרחים ורודים כמו ראשי סיכות. עלים עדינים מתקפלים בלילה.",
    tips: "מתאים לגינה אסייתית — עלים עדינים ופרחים קסומים.",
  },
  // ---- עצים ----
  {
    id: 33,
    nameHe: "ברוש",
    nameLatin: "Cupressus sempervirens",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "15-25 מטר",
    description: "עץ ירוק-עד צר ומוארך האייקוני של הנוף הים-תיכוני. עמיד לחום ולצורת.",
    tips: "שתול בשורות ליצירת מסך רוח ופרטיות.",
  },
  {
    id: 34,
    nameHe: "אורן ירושלים",
    nameLatin: "Pinus halepensis",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "10-20 מטר",
    bloomSeason: "אביב",
    description: "עץ מחטני ים-תיכוני עמיד בחום ובצורת. מאפיין את נוף ההרים בישראל.",
    tips: "ביוש ביסוס ראשוני — לאחר מכן כמעט אינו צריך השקיה.",
  },
  {
    id: 35,
    nameHe: "אקליפטוס",
    nameLatin: "Eucalyptus camaldulensis",
    categories: ["trees"],
    sun: "full",
    water: "medium",
    height: "15-30 מטר",
    description: "עץ אוסטרלי גדל-מהיר עם עלים בריחניים. עמיד לחום ולחיות מים.",
    tips: "שורשים עמוקים ומרחיקים — שמור מרחק ממבנים.",
  },
  {
    id: 36,
    nameHe: "ג'ינקו",
    nameLatin: "Ginkgo biloba",
    categories: ["trees"],
    sun: "full",
    water: "medium",
    height: "15-25 מטר",
    bloomSeason: "אביב",
    description: "עץ עתיק יומין - 'מאובן חי'. עלים ייחודיים בצורת מניפה צהובים בסתיו.",
    tips: "בחר עצים זכרים בלבד — פרי הנקבה בעל ריח חזק.",
  },
  {
    id: 37,
    nameHe: "ערבה בוכייה",
    nameLatin: "Salix babylonica",
    categories: ["trees"],
    sun: "full",
    water: "high",
    height: "8-15 מטר",
    description: "עץ עם ענפים תלויים רומנטיים. אוהב מים — מושלם ליד בריכות ואגמים.",
    tips: "שתול רחוק מצנרת — שורשיו מחפשים מים בנמרצות.",
  },
  {
    id: 38,
    nameHe: "חרוב",
    nameLatin: "Ceratonia siliqua",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "5-10 מטר",
    description: "עץ ים-תיכוני ירוק-עד עמיד מאוד. קרוביו מניבים תרמילים מתוקים.",
    tips: "עמיד בצורת ובחום — מתאים לגינה ים-תיכונית.",
  },
  {
    id: 39,
    nameHe: "שקמה",
    nameLatin: "Ficus sycomorus",
    categories: ["trees"],
    sun: "full",
    water: "medium",
    height: "10-20 מטר",
    description: "עץ תנ\"כי ירוק-עד עם גזע מרשים וצל נרחב. מוזכר בכתבי הקודש.",
    tips: "עץ גדול מאוד — מתאים לשטחים גדולים בלבד.",
  },
  {
    id: 40,
    nameHe: "אשל",
    nameLatin: "Tamarix aphylla",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "5-10 מטר",
    description: "עץ חסין בצורה ומליחות. פרחים ורודים עדינים ועלים כחלחלים.",
    tips: "אחד העצים העמידים ביותר לתנאי מדבר ואדמה מלוחה.",
  },
  // ---- שיחים ----
  {
    id: 41,
    nameHe: "ורד",
    nameLatin: "Rosa × hybrida",
    categories: ["shrubs"],
    sun: "full",
    water: "medium",
    height: "0.5-2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "שיח הפרח הקלאסי והאהוב ביותר. מגוון אינסופי של צבעים וצורות.",
    tips: "גזום בסוף החורף והדש בסידן וזרחן לפריחה מרשימה.",
  },
  {
    id: 42,
    nameHe: "הביסקוס",
    nameLatin: "Hibiscus rosa-sinensis",
    categories: ["shrubs"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "כל השנה",
    description: "שיח טרופי עם פרחים ענקיים צבעוניים. פורח כמעט כל השנה בסביבה חמה.",
    tips: "גזום בין עונות לשמירת צורה קומפקטית ופריחה מרובה.",
  },
  {
    id: 43,
    nameHe: "פלומריה",
    nameLatin: "Plumeria rubra",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח/עץ קטן עם פרחים ריחניים מרהיבים. מסמל את ההוואי וחיי הטרופיים.",
    tips: "עמיד לצורת — מחרוזות פרחים לריח שכיח בגינות טרופיות.",
  },
  {
    id: 44,
    nameHe: "נריום",
    nameLatin: "Nerium oleander",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "2-4 מטר",
    bloomSeason: "קיץ",
    description: "שיח עמיד בצורה עם פרחים ורודים/לבנים/אדומים. זהירות - רעיל מאוד.",
    tips: "אל תשרוף ענפים — עשן גם הוא רעיל.",
  },
  {
    id: 45,
    nameHe: "לבנדר",
    nameLatin: "Lavandula angustifolia",
    categories: ["shrubs", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח ריחני כחלכחל-סגול. מושך פרפרים ודבורים, דוחה מזיקים.",
    tips: "גזום שליש מהצמח אחרי הפריחה לשמירה על צורה קומפקטית.",
  },
  {
    id: 46,
    nameHe: "רוזמרין",
    nameLatin: "Rosmarinus officinalis",
    categories: ["shrubs", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-1.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח ארומטי ים-תיכוני עם עלים עדינים ופרחים כחולים. בישול ונוי כאחד.",
    tips: "ניקוז טוב חיוני — שורשי ריקבון ממים עומדים.",
  },
  {
    id: 47,
    nameHe: "פלומבגו",
    nameLatin: "Plumbago auriculata",
    categories: ["shrubs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח עם פרחים תכולים-שמיים מרהיבים. פורח ממושך ואוהב חום.",
    tips: "גזום בסוף החורף לצמיחה רעננה ופריחה מרשימה.",
  },
  {
    id: 48,
    nameHe: "אדניום",
    nameLatin: "Adenium obesum",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "0.5-2 מטר",
    bloomSeason: "קיץ",
    description: "שיח סוקולנטי עם גזע תפוח ופרחים ורודים/אדומים. מוכר כ'ורד המדבר'.",
    tips: "לא להשקות בחורף — הצמח נמצא בשינה.",
  },
  {
    id: 49,
    nameHe: "יסמין ערבי",
    nameLatin: "Jasminum sambac",
    categories: ["shrubs", "climbers"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "שיח/מטפס עם פרחים לבנים ריחניים מאוד. ריח אינטנסיבי בקיץ.",
    tips: "הסיר פרחים קמלים לעידוד פריחה מתמשכת.",
  },
  {
    id: 50,
    nameHe: "גרניום",
    nameLatin: "Pelargonium × hortorum",
    categories: ["shrubs", "perennials"],
    sun: "full",
    water: "medium",
    height: "0.3-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "שיח פורח ועמיד עם עלים ריחניים. מגוון רחב של צבעים ומתאים לעציצים.",
    tips: "הסר עלים וגבעולים יבשים לפריחה מתמשכת.",
  },
  {
    id: 51,
    nameHe: "דורמנה",
    nameLatin: "Teucrium fruticans",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח ים-תיכוני עם עלים כסופים ופרחים כחולים. עמיד לחום ולצורת.",
    tips: "גזום לאחר הפריחה לשמירת צורה קומפקטית.",
  },
  {
    id: 52,
    nameHe: "מירטוס",
    nameLatin: "Myrtus communis",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "שיח ים-תיכוני ריחני עם פרחים לבנים קטנים ועלים מבריקים.",
    tips: "מתאים לגידור ולעיצוב טופיאר — מקבל גיזום היטב.",
  },
  // ---- שיחי הסתרה ----
  {
    id: 53,
    nameHe: "פיטוספורום",
    nameLatin: "Pittosporum tobira",
    categories: ["privacy-shrubs"],
    sun: "partial",
    water: "low",
    height: "1-4 מטר",
    bloomSeason: "אביב",
    description: "שיח הסתרה עמיד עם עלים מבריקים ופרחים ריחניים לבנים. עמיד לצל.",
    tips: "גדר עמידה ומצוינת — כמעט אינה צריכה טיפול.",
  },
  {
    id: 54,
    nameHe: "ליגוסטרום",
    nameLatin: "Ligustrum japonicum",
    categories: ["privacy-shrubs"],
    sun: "partial",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "שיח הסתרה עם עלים מבריקים ופרחים לבנים ריחניים. גדל מהיר ועמיד.",
    tips: "גזם 2-3 פעמים בשנה לגדר צפופה ומסודרת.",
  },
  {
    id: 55,
    nameHe: "פוטיניה",
    nameLatin: "Photinia × fraseri",
    categories: ["privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "אביב",
    description: "שיח הסתרה עם עלים חדשים בצבע אדום בולט. יוצר גדר ירוקה צפופה.",
    tips: "העלים החדשים אדומים — גזום לעידוד צמיחה צבעונית.",
  },
  {
    id: 56,
    nameHe: "וויבורנום",
    nameLatin: "Viburnum odoratissimum",
    categories: ["privacy-shrubs"],
    sun: "partial",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "אביב",
    description: "שיח הסתרה עם עלים ירוקים מבריקים ופרחים לבנים ריחניים. גדל מהיר.",
    tips: "אחד הגדרות הריחניות ביותר — מושלם ליד פתחי בית.",
  },
  {
    id: 57,
    nameHe: "ספרינה",
    nameLatin: "Escallonia rubra",
    categories: ["privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח הסתרה עם פרחים ורודים-אדומים קטנים. עמיד לרוח ולמלח.",
    tips: "מתאים לאזורי חוף — עמיד לרוח ים מלוחה.",
  },
  {
    id: 58,
    nameHe: "אבליה",
    nameLatin: "Abelia × grandiflora",
    categories: ["privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח מטה גמיש עם פרחים לבנים קטנים. פורח ממושך ומושך פרפרים.",
    tips: "גזום קלות לשמירת צורה — אינו אוהב גיזום נמרץ.",
  },
  {
    id: 59,
    nameHe: "דפנה",
    nameLatin: "Viburnum tinus",
    categories: ["privacy-shrubs", "shade"],
    sun: "partial",
    water: "low",
    height: "2-4 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח הסתרה ירוק-עד הסובל צל. פורח בחורף בפרחים לבנים ורוד.",
    tips: "אחד מהשיחים הטובים ביותר לצל — עמיד ויפה.",
  },
  {
    id: 60,
    nameHe: "לנטנה",
    nameLatin: "Lantana camara",
    categories: ["shrubs", "privacy-shrubs", "perennials"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "כל השנה",
    description: "שיח צבעוני עם פרחים המחליפים צבע — צהוב, כתום, ורוד. פורח כל השנה.",
    tips: "עמיד בצורת ומושך פרפרים — אידיאלי לגינת פרפרים.",
  },
  // ---- רב שנתיים ----
  {
    id: 61,
    nameHe: "סטרליציה",
    nameLatin: "Strelitzia reginae",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "1-1.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח ייחודי בצורת ראש ציפור טרופי. אחד הפרחים המרשימים ביותר לגינה.",
    tips: "דרוש אור מלא ואדמה ניקוזית להבטחת פריחה.",
  },
  {
    id: 62,
    nameHe: "אגפנטוס",
    nameLatin: "Agapanthus africanus",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח פורח עם אשכולות פרחים כחולים/לבנים על גבעולים ארוכים. עמיד.",
    tips: "משגשג כשמוצף שמש — כמות גבוהה של פרחים בצפיפות.",
  },
  {
    id: 63,
    nameHe: "קנה פרח",
    nameLatin: "Canna indica",
    categories: ["perennials", "geophytes"],
    sun: "full",
    water: "high",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "צמח טרופי עם עלים גדולים ופרחים ורודים/כתומים/אדומים. מרשים ובולט.",
    tips: "אוהב מים — השקה שוטפת בקיץ חיונית.",
  },
  {
    id: 64,
    nameHe: "אכינצאה",
    nameLatin: "Echinacea purpurea",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח מרפא ונוי עם פרחים סגולים עם מרכז קוני. מושך חרקים מועילים.",
    tips: "השאר ראשי פרחים יבשים לחורף — ציפורים אוהבות את הזרעים.",
  },
  {
    id: 65,
    nameHe: "רודבקיה",
    nameLatin: "Rudbeckia hirta",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.5-1 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח שמשי צהוב עם מרכז חום כהה. עמיד ופורח ממושך.",
    tips: "גזם פרחים קמלים להארכת עונת הפריחה.",
  },
  {
    id: 66,
    nameHe: "אסטרומריה",
    nameLatin: "Alstroemeria",
    categories: ["perennials"],
    sun: "partial",
    water: "medium",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "פרח כרוך בצבעים מרהיבים — ורוד, כתום, לבן עם פסים. מתאים לאגרטלים.",
    tips: "עמיד בקטיף — נמשך שבועות באגרטל.",
  },
  {
    id: 67,
    nameHe: "גזניה",
    nameLatin: "Gazania rigens",
    categories: ["perennials"],
    sun: "full",
    water: "low",
    height: "0.2-0.4 מטר",
    bloomSeason: "אביב-סתיו",
    description: "פרח אפריקאי צבעוני הפותח בשמש וסוגר בצל. עמיד בצורת.",
    tips: "מצוין לכיסוי קרקע במדרונות — עמיד ומרהיב.",
  },
  {
    id: 68,
    nameHe: "דיאנתוס",
    nameLatin: "Dianthus caryophyllus",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.3-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ציפורן ריחני בצבעים מגוונים — ורוד, אדום, לבן. מתאים לאגרטלים.",
    tips: "גזום לאחר הפריחה לגל פריחה נוסף.",
  },
  {
    id: 69,
    nameHe: "ליאטריס",
    nameLatin: "Liatris spicata",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.4-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח שיבולת עם פרחים סגולים-ורודים פותחים מלמעלה למטה. ייחודי.",
    tips: "מצוין לגינת פרפרים — נמשך היטב כפרח חתוך.",
  },
  {
    id: 70,
    nameHe: "פנסטמון",
    nameLatin: "Penstemon digitalis",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-קיץ",
    description: "צמח נוי אמריקאי עם פרחים כמו פעמוניות לבנות-ורודות. מושך יונקים.",
    tips: "עמיד בצורת — מצוין לגינה אמריקאית.",
  },
  {
    id: 71,
    nameHe: "סיגל",
    nameLatin: "Viola odorata",
    categories: ["perennials", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.2 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח קטן וריחני עם עלים לבביים. גדל בצל ופורח בחורף ובאביב.",
    tips: "מתאים לכיסוי קרקע תחת עצים — אוהב צל קליל.",
  },
  {
    id: 72,
    nameHe: "עקיזה",
    nameLatin: "Achillea millefolium",
    categories: ["perennials"],
    sun: "full",
    water: "low",
    height: "0.4-0.8 מטר",
    bloomSeason: "קיץ",
    description: "צמח מרפא ונוי עם פרחים שטוחים בצבעים שונים. עמיד בצורת ובחום.",
    tips: "יבש היטב כפרח חתוך לשמירת צבע.",
  },
  {
    id: 73,
    nameHe: "סגה",
    nameLatin: "Salvia officinalis",
    categories: ["perennials", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-0.8 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח ריחני ים-תיכוני בעל עלים כסופים ופרחים כחולים. מרפא ותבלין.",
    tips: "גזום לאחר הפריחה לשמירת עלים ריחניים ורעננים.",
  },
  // ---- עונתיים ----
  {
    id: 74,
    nameHe: "פטוניה",
    nameLatin: "Petunia × hybrida",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "פרח עונתי צבעוני מאוד עם מגוון אינסופי של גוונים. מתאים לעציצים ולתלויים.",
    tips: "גזום קלות אחת לשבועיים להמשך פריחה שופעת.",
  },
  {
    id: 75,
    nameHe: "חמניות",
    nameLatin: "Helianthus annuus",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "פרח השמש הסובב פנים לכיוון האור. פרחים ענקיים צהובים. עגב ה-שמחה.",
    tips: "זרע ישירות בשטח — אינה אוהבת השתלה.",
  },
  {
    id: 76,
    nameHe: "ציניה",
    nameLatin: "Zinnia elegans",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "0.3-0.9 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח עונתי צבעוני מאוד עמיד לחום. פריחה ממושכת מקיץ עד סתיו.",
    tips: "גזום פרחים קמלים להארכת עונת הפריחה.",
  },
  {
    id: 77,
    nameHe: "קוסמוס",
    nameLatin: "Cosmos bipinnatus",
    categories: ["annuals"],
    sun: "full",
    water: "low",
    height: "0.6-1.2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח גבוה ועדין עם עלים דמויי נוצות ופרחים ורודים/לבנים/סגולים.",
    tips: "עמיד בצורת — אחד מהפרחים הקלים ביותר לגידול.",
  },
  {
    id: 78,
    nameHe: "טגטס",
    nameLatin: "Tagetes patula",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "ציפורן אפריקאית עם פרחים כתומים-צהובים. דוחה מזיקים מהגינה.",
    tips: "שתול בגינת ירקות לדחיית נמטודות ומזיקים.",
  },
  {
    id: 79,
    nameHe: "אנמונה",
    nameLatin: "Anemone coronaria",
    categories: ["annuals", "geophytes"],
    sun: "full",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח בר ישראלי מוכר בצבעים אדום, לבן, סגול. פורח בשדות בחורף.",
    tips: "שתול כפקעות בסתיו לפריחה בחורף-אביב.",
  },
  {
    id: 80,
    nameHe: "פרג",
    nameLatin: "Papaver rhoeas",
    categories: ["annuals"],
    sun: "full",
    water: "low",
    height: "0.3-0.9 מטר",
    bloomSeason: "אביב",
    description: "פרח בר ישראלי אדום-לוהט הפורח בשדות בסוף החורף. עדין ויפהפה.",
    tips: "פזר זרעים בסתיו לפריחה ספונטנית באביב.",
  },
  {
    id: 81,
    nameHe: "נסטורציום",
    nameLatin: "Tropaeolum majus",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.3-3 מטר",
    bloomSeason: "קיץ",
    description: "פרח אכיל עם פרחים כתומים-צהובים. העלים, הפרחים וזרעי הקפרס אכילים.",
    tips: "פרח ועלים אכילים — מצוין לסלטים.",
  },
  {
    id: 82,
    nameHe: "ארנבנית",
    nameLatin: "Antirrhinum majus",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "0.3-0.8 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח בצורת פרפר עם שפתיים הנסגרות. מגוון צבעים ורצועות.",
    tips: "שתול בסתיו לפריחה עשירה בחורף ובאביב.",
  },
  {
    id: 83,
    nameHe: "לוביליה",
    nameLatin: "Lobelia erinus",
    categories: ["annuals", "trailing"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "צמח נשפך קטן עם פרחים כחולים/לבנים עדינים. מצוין לתלויים ולשוליים.",
    tips: "גזום לאחר הפריחה הראשונה לגל פריחה נוסף.",
  },
  {
    id: 84,
    nameHe: "קליברכואה",
    nameLatin: "Calibrachoa",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.1-0.3 מטר",
    bloomSeason: "כל השנה",
    description: "פטוניה מיניאטורית עם אלפי פרחים קטנטנים. מצוין לסלי תלייה ועציצים.",
    tips: "לא צריך להסיר פרחים קמלים — פורח מעצמו.",
  },
  {
    id: 85,
    nameHe: "ורבנה",
    nameLatin: "Verbena × hybrida",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "צמח נשפך ופורח בצבעים מגוונים. מצוין לכיסוי קרקע ולתלויים.",
    tips: "גזום קלות להמשך פריחה צפופה.",
  },
  // ---- צמחיה לבית ----
  {
    id: 86,
    nameHe: "מונסטרה",
    nameLatin: "Monstera deliciosa",
    categories: ["indoor"],
    sun: "shade",
    water: "medium",
    height: "1-5 מטר",
    description: "צמח בית אייקוני עם עלים גדולים מחוררים. סמל לעיצוב טרופי מודרני.",
    tips: "נגב עלים בלחית לניקוי ולשמירת ברק.",
  },
  {
    id: 87,
    nameHe: "פוטוס",
    nameLatin: "Epipremnum aureum",
    categories: ["indoor", "trailing"],
    sun: "shade",
    water: "medium",
    height: "מטפס",
    description: "צמח בית עמיד ביותר עם עלים לבביים ירוקים-צהובים. כמעט אי-אפשר להרוג.",
    tips: "מנקה אוויר — מצוין לשטחים פנים ללא אור טבעי.",
  },
  {
    id: 88,
    nameHe: "סנסוויריה",
    nameLatin: "Sansevieria trifasciata",
    categories: ["indoor"],
    sun: "partial",
    water: "low",
    height: "0.3-1.2 מטר",
    description: "צמח בית עמיד ביותר עם עלים חרביים ישרים. מנקה אוויר ועמיד בהזנחה.",
    tips: "לא להשקות יתר — שורש ריקבון הוא הסכנה היחידה.",
  },
  {
    id: 89,
    nameHe: "פילודנדרון",
    nameLatin: "Philodendron hederaceum",
    categories: ["indoor", "trailing"],
    sun: "shade",
    water: "medium",
    height: "0.5-3 מטר",
    description: "צמח בית נשפך עם עלים לבביים ירוקים. גדל מהיר ועמיד לתנאים שונים.",
    tips: "הסר עלים צהובים מיד — סימן להשקיה יתר.",
  },
  {
    id: 90,
    nameHe: "פיקוס בנג'מין",
    nameLatin: "Ficus benjamina",
    categories: ["indoor"],
    sun: "partial",
    water: "medium",
    height: "1-3 מטר (בבית)",
    description: "עץ בית קלאסי עם עלים קטנים מבריקים. מרשים ומנקה אוויר.",
    tips: "אל תזיז לעתים קרובות — מגיב בנשירת עלים לשינויי מיקום.",
  },
  {
    id: 91,
    nameHe: "קלתיאה",
    nameLatin: "Calathea orbifolia",
    categories: ["indoor"],
    sun: "shade",
    water: "high",
    height: "0.5-0.9 מטר",
    description: "צמח בית מפואר עם עלים מפוספסים כסוף-ירוק. עלים נסגרים בלילה.",
    tips: "השתמש במי גשמים או מי שתייה — רגיש לכלור.",
  },
  {
    id: 92,
    nameHe: "ספאתיפילום",
    nameLatin: "Spathiphyllum wallisii",
    categories: ["indoor"],
    sun: "shade",
    water: "medium",
    height: "0.4-0.8 מטר",
    bloomSeason: "קיץ",
    description: "צמח בית עם פרחים לבנים אלגנטיים ועלים כהים ומבריקים. מנקה אוויר.",
    tips: "מאותת צמא בשמלת עלים — השקה מיידית תחזיר אותו.",
  },
  {
    id: 93,
    nameHe: "דרקנה",
    nameLatin: "Dracaena fragrans",
    categories: ["indoor"],
    sun: "partial",
    water: "low",
    height: "1-2 מטר (בבית)",
    description: "צמח בית גבוה עם עלים פסים רחבים. סובל תנאי אור שונים ומנקה אוויר.",
    tips: "קצות עלים חומים מסמנים מים קשים — עבור למי גשמים.",
  },
  {
    id: 94,
    nameHe: "פלמת ארקה",
    nameLatin: "Dypsis lutescens",
    categories: ["indoor", "ornamental-trees"],
    sun: "partial",
    water: "medium",
    height: "1-2 מטר (בבית)",
    description: "דקל בית אלגנטי עם גזעים צהבהבים ועלים ארוכים. מעניק אווירה טרופית.",
    tips: "אחד ממנקי האוויר הטובים ביותר — לפי נאסא.",
  },
  {
    id: 95,
    nameHe: "אנתוריום",
    nameLatin: "Anthurium andraeanum",
    categories: ["indoor"],
    sun: "shade",
    water: "medium",
    height: "0.4-0.8 מטר",
    bloomSeason: "כל השנה",
    description: "צמח בית עם פרחים לב-אדומים מבריקים. פורח כמעט כל השנה.",
    tips: "הגן מפני אור שמש ישיר — שורף את העלים.",
  },
  {
    id: 96,
    nameHe: "פיקוס ליראטה",
    nameLatin: "Ficus lyrata",
    categories: ["indoor"],
    sun: "partial",
    water: "medium",
    height: "1-2 מטר (בבית)",
    description: "עץ בית מודרני עם עלים ענקיים בצורת כינור. טרנד עיצוב פנים מרכזי.",
    tips: "ניגב עלים בלחות ותן אור מספיק — גדל לאט.",
  },
  {
    id: 97,
    nameHe: "זמיוקולקס",
    nameLatin: "Zamioculcas zamiifolia",
    categories: ["indoor"],
    sun: "shade",
    water: "low",
    height: "0.5-1 מטר",
    description: "צמח בית עמיד מאוד עם עלים מבריקים כהים. כמעט בלתי ניתן להרוג.",
    tips: "שוכח השקיה חודשים? לא נורא — ZZ מחכה בסבלנות.",
  },
  {
    id: 98,
    nameHe: "אספידיסטרה",
    nameLatin: "Aspidistra elatior",
    categories: ["indoor", "shade"],
    sun: "shade",
    water: "low",
    height: "0.5-0.8 מטר",
    description: "צמח עמיד ביותר עם עלים כהים ורחבים. מכונה 'צמח הברזל' בשל עמידותו.",
    tips: "מתאים לפינות חשוכות שאף צמח אחר לא שורד בהן.",
  },
  // ---- סוקולנטים ----
  {
    id: 99,
    nameHe: "אלוורה",
    nameLatin: "Aloe vera",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "סוקולנט מרפא מפורסם עם עלים בשרניים מלאי ג'ל מרגיע לעור.",
    tips: "שבור עלה ישן ל כוויות ועקיצות — ג'ל הוא תרופת טבע.",
  },
  {
    id: 100,
    nameHe: "קרסולה",
    nameLatin: "Crassula ovata",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.5-1.5 מטר",
    bloomSeason: "חורף",
    description: "סוקולנט עמיד עם עלים עגולים ומבריקים. מכונה 'עץ הזהב' ומסמל מזל.",
    tips: "כמעט אינו מת — אחד הסוקולנטים הקלים לגידול.",
  },
  {
    id: 101,
    nameHe: "אכאוריה",
    nameLatin: "Echeveria elegans",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב",
    description: "סוקולנט ורדי מרהיב בצורת ורד. עלים עבים כסופים-כחלחלים.",
    tips: "הרחק ממים מלמעלה — מים בין העלים גורמים לריקבון.",
  },
  {
    id: 102,
    nameHe: "סדום",
    nameLatin: "Sedum rubrotinctum",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "חורף",
    description: "סוקולנט עם עלים עגולים-בשרניים בצבע ירוק-אדום. מכונה 'ג'לי-בינס'.",
    tips: "אדום יותר בשמש — ירוק בצל. אחד הפשוטים לרבייה.",
  },
  {
    id: 103,
    nameHe: "הוורתיה",
    nameLatin: "Haworthia attenuata",
    categories: ["succulents", "indoor"],
    sun: "partial",
    water: "low",
    height: "0.1-0.2 מטר",
    description: "סוקולנט קטן עם פסים לבנים על עלים ירוקים. סובל צל טוב יותר מרוב הסוקולנטים.",
    tips: "אחד הסוקולנטים המעטים המתאימים לחלון צפוני.",
  },
  {
    id: 104,
    nameHe: "קלנחואה",
    nameLatin: "Kalanchoe blossfeldiana",
    categories: ["succulents", "indoor"],
    sun: "full",
    water: "low",
    height: "0.2-0.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "סוקולנט פורח עם פרחים קטנים-בולטים בכתום, צהוב, ורוד, אדום.",
    tips: "לאחר הפריחה: גזום, הפחת מים והפרח שוב.",
  },
  {
    id: 105,
    nameHe: "אגבה",
    nameLatin: "Agave americana",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "פעם בחיים",
    description: "סוקולנט ענק עם עלים שנוניים כחולים-אפורים. פורח פעם אחת בחייו.",
    tips: "זהירות מקצוות חדות — מתאים לגינה רשמית ובולטת.",
  },
  {
    id: 106,
    nameHe: "אלו ארבורסנס",
    nameLatin: "Aloe arborescens",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    bloomSeason: "חורף",
    description: "אלוורה גדולה עם פרחים כתומים-אדומים בחורף. עמידה מאוד ויפה.",
    tips: "פורח בחורף כשרוב הגינה ישנה — ספק צבע לעונה הקרה.",
  },
  {
    id: 107,
    nameHe: "גרפטופטלום",
    nameLatin: "Graptopetalum paraguayense",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    description: "סוקולנט ורדי קטן עם עלים ורודים-סגולים. קל לרבייה מעלים בודדים.",
    tips: "נפרד עלה מהגבעול, הנח על אדמה — שורש לבד.",
  },
  {
    id: 108,
    nameHe: "פורסלאן",
    nameLatin: "Portulaca grandiflora",
    categories: ["succulents", "annuals", "trailing"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "קיץ",
    description: "צמח נשפך עם פרחים ורדיים-ססגוניים הנפתחים בשמש. עמיד לחום.",
    tips: "פותח בשמש וסוגר בצל — מרביץ תצוגה ביום בלבד.",
  },
  // ---- קקטוסים ----
  {
    id: 109,
    nameHe: "צבר",
    nameLatin: "Opuntia ficus-indica",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "1-5 מטר",
    bloomSeason: "אביב-קיץ",
    description: "קקטוס ישראלי אייקוני עם פרי אכיל (תאנת-הודיה). נותן גדר עמידה.",
    tips: "פרי אכיל — השתמש בכפפות עבות לקטיף.",
  },
  {
    id: 110,
    nameHe: "קרקטוס",
    nameLatin: "Cereus peruvianus",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "2-6 מטר",
    bloomSeason: "לילה",
    description: "קקטוס עמודי גבוה ומרשים. פורח בלילה בפרחים גדולים לבנים.",
    tips: "אחד הקקטוסים הגבוהים ביותר — מרשים כנקודת מוקד בגינה.",
  },
  {
    id: 111,
    nameHe: "פרחינוקקטוס",
    nameLatin: "Ferocactus cylindraceus",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "0.3-1 מטר",
    bloomSeason: "אביב",
    description: "קקטוס גלילי עם קוצים צבעוניים חזקים. נקרא 'חבית קקטוס'.",
    tips: "לא להשקות בחורף בכלל — רגיש לריקבון בקור.",
  },
  {
    id: 112,
    nameHe: "ממילריה",
    nameLatin: "Mammillaria elongata",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "אביב",
    description: "קקטוס קטן-עגלגל עם קוצים דקים זהובים. מניב שכים צהובים קטנטנים.",
    tips: "קל לגידול בעציץ — אידיאלי לאוספי קקטוסים.",
  },
  {
    id: 113,
    nameHe: "איצ'ינוקצ'טוס",
    nameLatin: "Echinocactus grusonii",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "0.3-0.8 מטר",
    description: "קקטוס ענק כדורי עם קוצים צהובים. מכונה 'כיסא החמות'. גדל לאט.",
    tips: "גדל לאט מאוד — קקטוס גדול הוא בן עשרות שנים.",
  },
  // ---- גיאופיטים ----
  {
    id: 114,
    nameHe: "צבעוני",
    nameLatin: "Tulipa gesneriana",
    categories: ["geophytes"],
    sun: "full",
    water: "medium",
    height: "0.2-0.6 מטר",
    bloomSeason: "אביב",
    description: "פרח אביב קלאסי בצבעים מרהיבים. מסמל את הופעת האביב בגינה.",
    tips: "שמור פקעות בקירור לפני שתילה — ישראל חמה מדי.",
  },
  {
    id: 115,
    nameHe: "נרקיס",
    nameLatin: "Narcissus tazetta",
    categories: ["geophytes"],
    sun: "full",
    water: "medium",
    height: "0.3-0.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח ריחני אהוב עם פרחים לבנים ומרכז צהוב. פורח בחורף-אביב.",
    tips: "שתול בסתיו — פרחים מרהיבים בפברואר-מרץ.",
  },
  {
    id: 116,
    nameHe: "רקפת",
    nameLatin: "Cyclamen persicum",
    categories: ["geophytes", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.3 מטר",
    bloomSeason: "חורף",
    description: "פרח חורפי עם פרחים ורודים-לבנים ועלים מנוקדים. פורח בצל.",
    tips: "השקה מלמטה בלבד — מים על הבצל גורמים לריקבון.",
  },
  {
    id: 117,
    nameHe: "גלדיולוס",
    nameLatin: "Gladiolus × hortulanus",
    categories: ["geophytes"],
    sun: "full",
    water: "medium",
    height: "0.6-1.2 מטר",
    bloomSeason: "קיץ",
    description: "פרח שיבולת גבוה עם פרחים צבעוניים גדולים לאורך הגבעול. לאגרטלים.",
    tips: "שתול פקעות בשלבים לפריחה מתמשכת לאורך הקיץ.",
  },
  {
    id: 118,
    nameHe: "אירוס",
    nameLatin: "Iris germanica",
    categories: ["geophytes"],
    sun: "full",
    water: "low",
    height: "0.3-1 מטר",
    bloomSeason: "אביב",
    description: "פרח אצילי עם עלים חרביים ופרחים מורכבים בסגול, לבן וכחול.",
    tips: "אל תשקה יתר — שורש עם ריקבון מסוכן.",
  },
  {
    id: 119,
    nameHe: "דהליה",
    nameLatin: "Dahlia pinnata",
    categories: ["geophytes"],
    sun: "full",
    water: "high",
    height: "0.3-1.5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח מפואר עם פרחים ענקיים בצורות ובצבעים מגוונים. מלכת הגינה.",
    tips: "הוצא פקעות מהאדמה בחורף לשמירה עד השנה הבאה.",
  },
  {
    id: 120,
    nameHe: "חצב",
    nameLatin: "Urginea maritima",
    categories: ["geophytes"],
    sun: "full",
    water: "low",
    height: "0.3-1.5 מטר",
    bloomSeason: "סתיו",
    description: "צמח בר ישראלי עם שיבולת פרחים לבנה. פורח בסתיו לפני הצצת העלים.",
    tips: "פורח בלי עלים בסתיו — ייחודי ומרתק לגינה מדיטרנית.",
  },
  {
    id: 121,
    nameHe: "מוסקרי",
    nameLatin: "Muscari armeniacum",
    categories: ["geophytes"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב",
    description: "פרח קטן-כחול בצורת אשכול ענבים. מבשר האביב הראשון בגינה.",
    tips: "שתול בסתיו לפריחה מוקדמת ומרהיבה באביב.",
  },
  // ---- עשבי תיבול ----
  {
    id: 122,
    nameHe: "בזיליקום",
    nameLatin: "Ocimum basilicum",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול אהוב עם עלים ריחניים. חיוני לבישול איטלקי ומדיטרני.",
    tips: "גזם ראשי פרחים מיד — פריחה מחלישה את הארומה.",
  },
  {
    id: 123,
    nameHe: "נענע",
    nameLatin: "Mentha × piperita",
    categories: ["herbs"],
    sun: "partial",
    water: "high",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול ריחני מאוד עם עלים מרעננים. מרחיב לכל הכיוונים.",
    tips: "שתול בעציץ — שורשים פולשניים כובשים את הגינה.",
  },
  {
    id: 124,
    nameHe: "תימין",
    nameLatin: "Thymus vulgaris",
    categories: ["herbs"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "אביב-קיץ",
    description: "עשב ים-תיכוני קטן ריחני. עמיד בצורת ובחום — מתאים לגינה ים-תיכונית.",
    tips: "כיסוי קרקע נהדר בין אבנים — עמיד ודקורטיבי.",
  },
  {
    id: 125,
    nameHe: "אורגנו",
    nameLatin: "Origanum vulgare",
    categories: ["herbs"],
    sun: "full",
    water: "low",
    height: "0.2-0.6 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול ים-תיכוני חיוני לפיצה ולבישול ים-תיכוני. עמיד ועצמאי.",
    tips: "קטיף מגדיל ריכוז שמנים — גזם לעתים קרובות.",
  },
  {
    id: 126,
    nameHe: "כוסברה",
    nameLatin: "Coriandrum sativum",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "אביב",
    description: "עשב תיבול עם ניחוח חזק ומיוחד. חיוני לבישול מזרחי, תימני ואסייתי.",
    tips: "שתול בסביבה קרירה — פורח מהר בחום ומאבד טעם.",
  },
  {
    id: 127,
    nameHe: "פטרוזיליה",
    nameLatin: "Petroselinum crispum",
    categories: ["herbs"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.5 מטר",
    description: "עשב תיבול מוכר ובסיסי לכל מטבח. עלים ירוקים עשירים בברזל.",
    tips: "גדל טוב גם בחצי-צל — מתאים לגינת מרפסת.",
  },
  {
    id: 128,
    nameHe: "שמיר",
    nameLatin: "Anethum graveolens",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול גבוה עם עלים עדינים כנוצות. חיוני לבישול ישראלי.",
    tips: "זרע ישירות — אינו אוהב השתלה. שמר לחות.",
  },
  {
    id: 129,
    nameHe: "לואיזה",
    nameLatin: "Aloysia citrodora",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "קיץ",
    description: "שיח תיבול עם ניחוח לימוני עז. מצוין להכנת תה ולשתייה קרה.",
    tips: "קצץ ל-צד ייבוש תה — טעמו משתפר עם הייבוש.",
  },
  {
    id: 130,
    nameHe: "מליסה",
    nameLatin: "Melissa officinalis",
    categories: ["herbs", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.3-0.8 מטר",
    bloomSeason: "קיץ",
    description: "עשב לימוני מרגיע. מצוין לתה הרגעה וסובל קצת צל.",
    tips: "גזם לפני הפריחה לשמירת ריח לימון עז.",
  },
  // ---- מטפסים ----
  {
    id: 131,
    nameHe: "יסמין",
    nameLatin: "Jasminum polyanthum",
    categories: ["climbers"],
    sun: "partial",
    water: "medium",
    height: "מטפס 3-6 מטר",
    bloomSeason: "חורף-אביב",
    description: "מטפס ריחני עם פרחים לבנים-ורודים. הריח מילא לילות חורף ישראליים.",
    tips: "גזום לאחר הפריחה להכנה לגל הפריחה הבא.",
  },
  {
    id: 132,
    nameHe: "פסיפלורה",
    nameLatin: "Passiflora caerulea",
    categories: ["climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 5-10 מטר",
    bloomSeason: "קיץ",
    description: "מטפס עם פרחים מרהיבים ומורכבים בכחול-לבן. פרי אכיל קטן.",
    tips: "גדל מהיר מאוד — דרוש גידור חזק ורשת תמיכה.",
  },
  {
    id: 133,
    nameHe: "קפריפוליום",
    nameLatin: "Lonicera japonica",
    categories: ["climbers", "shade"],
    sun: "partial",
    water: "medium",
    height: "מטפס 4-10 מטר",
    bloomSeason: "קיץ",
    description: "מטפס ריחני עם פרחים צהובים-לבנים. עמיד בצל ובחום.",
    tips: "יכול לכסות גדר כולה — גדל מהיר בתנאים מגוונים.",
  },
  {
    id: 134,
    nameHe: "מנדוויליה",
    nameLatin: "Mandevilla sanderi",
    categories: ["climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 3-5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "מטפס טרופי עם פרחים ורודים-אדומים גדולים. מרשים על פרגולות וגדרות.",
    tips: "אינו עמיד לקרה — הכנס לבית בחורף.",
  },
  {
    id: 135,
    nameHe: "כרך",
    nameLatin: "Ipomoea purpurea",
    categories: ["climbers", "annuals"],
    sun: "full",
    water: "medium",
    height: "מטפס 3-5 מטר",
    bloomSeason: "קיץ",
    description: "מטפס שנתי מהיר עם פרחים סגולים-ורודים בצורת קול. כסוי מהיר.",
    tips: "גדל ב-6 שבועות מזרע — כיסוי מהיר ביותר לגינה.",
  },
  // ---- עונתיים חורף ----
  {
    id: 137,
    nameHe: "פנסי",
    nameLatin: "Viola × wittrockiana",
    categories: ["winter-annuals", "annuals"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.3 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרחים צבעוניים עם 'פרצוף' ייחודי. פורח בחורף ונהנה מטמפרטורות קרירות.",
    tips: "השקה מינימלית בחורף.",
  },
  {
    id: 138,
    nameHe: "פרמולה",
    nameLatin: "Primula vulgaris",
    categories: ["winter-annuals", "annuals"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.2 מטר",
    bloomSeason: "חורף",
    description: "פרחים צבעוניים עדינים הפורחים בלב החורף. מושלם לעציצים ולשטיחים.",
  },
  {
    id: 139,
    nameHe: "קלצאולריה",
    nameLatin: "Calceolaria × herbeohybrida",
    categories: ["winter-annuals", "annuals"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרחים ייחודיים בצורת כפות נעליים בגוונים צבעוניים. יפה כצמח עציץ לחורף.",
  },
  {
    id: 140,
    nameHe: "ציקלמן",
    nameLatin: "Cyclamen persicum",
    categories: ["winter-annuals", "geophytes", "indoor"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.3 מטר",
    bloomSeason: "חורף",
    description: "פרח חורפי מוכר עם עלים מנוקדים ופרחים ורודים-לבנים. פורח בצל ובחורף.",
  },
  {
    id: 141,
    nameHe: "כלנית",
    nameLatin: "Anemone coronaria",
    categories: ["winter-annuals", "geophytes"],
    sun: "full",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח הבר הישראלי האייקוני. פרחים אדומים, לבנים וסגולים. סמל לאביב הישראלי.",
  },
  {
    id: 142,
    nameHe: "נרקיס שדה",
    nameLatin: "Narcissus tazetta",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.5 מטר",
    bloomSeason: "חורף",
    description: "פרח בר ישראלי עם ריח נפלא. גדל בבצלים ופורח בינואר-פברואר.",
  },
  {
    id: 143,
    nameHe: "חרצית חורף",
    nameLatin: "Chrysanthemum paludosum",
    categories: ["winter-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "חורף-אביב",
    description: "חרצית קטנה ולבנה הפורחת בשפע בחורף. מצוינת לשטיחי גינה ולעציצים.",
  },
  {
    id: 144,
    nameHe: "לבנה ימית",
    nameLatin: "Lobularia maritima",
    categories: ["winter-annuals", "annuals", "trailing"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "חורף-אביב",
    description: "שטיח לבן עדין בעל ריח מתוק. מצוין כשתיל קצה.",
  },
  {
    id: 145,
    nameHe: "צינרריה",
    nameLatin: "Pericallis × hybrida",
    categories: ["winter-annuals", "annuals"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרחים צבעוניים עם מרכז לבן ועלים גדולים. מרהיב כצמח עציץ בחורף.",
  },
  {
    id: 146,
    nameHe: "אפונת הנוי",
    nameLatin: "Lathyrus odoratus",
    categories: ["winter-annuals", "annuals", "climbers"],
    sun: "full",
    water: "medium",
    height: "0.5-2 מטר",
    bloomSeason: "חורף-אביב",
    description: "מטפס עדין עם פרחים ריחניים בגוונים רבים. גדל מהר בחורף.",
  },
  {
    id: 147,
    nameHe: "גרדניה",
    nameLatin: "Gardenia jasminoides",
    categories: ["winter-annuals", "shrubs"],
    sun: "partial",
    water: "medium",
    height: "0.5-2 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח עם פרחים לבנים ריחניים בעלי ניחוח חזק. אחד הצמחים הריחניים ביותר.",
  },
  {
    id: 148,
    nameHe: "איריס",
    nameLatin: "Iris germanica",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "low",
    height: "0.4-1 מטר",
    bloomSeason: "אביב",
    description: "פרח אצולה עם עלי כותרת גדולים ויפים. קיים במגוון צבעים.",
  },
  {
    id: 149,
    nameHe: "טוליפ",
    nameLatin: "Tulipa gesneriana",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "medium",
    height: "0.2-0.6 מטר",
    bloomSeason: "אביב",
    description: "בצל פורח בצבעים מרהיבים. דורש קרה לצורך פריחה.",
  },
  {
    id: 150,
    nameHe: "היציינת",
    nameLatin: "Hyacinthus orientalis",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "medium",
    height: "0.2-0.3 מטר",
    bloomSeason: "חורף-אביב",
    description: "בצל ריחני עם אשכול פרחים צפוף. ריח חזק ומתוק.",
  },
  {
    id: 151,
    nameHe: "מוסקרי כחול",
    nameLatin: "Muscari armeniacum",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב",
    description: "בצל קטן עם אשכולות פרחים כחולים-סגולים. מצוין לשטיחים.",
  },
  {
    id: 152,
    nameHe: "פרג שדה",
    nameLatin: "Papaver rhoeas",
    categories: ["winter-annuals", "annuals"],
    sun: "full",
    water: "low",
    height: "0.3-0.9 מטר",
    bloomSeason: "אביב",
    description: "פרג השדה הישראלי האדום. פורח בריבוי עצום בשדות בחודשי אביב.",
  },
  {
    id: 153,
    nameHe: "מאתיולה",
    nameLatin: "Matthiola incana",
    categories: ["winter-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.3-0.8 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרחים ריחניים צפופים על שיבולות גבוהות בגוונים ורוד, לבן וסגול.",
  },
  {
    id: 154,
    nameHe: "בלית גנים",
    nameLatin: "Bellis perennis",
    categories: ["winter-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.1-0.2 מטר",
    bloomSeason: "חורף-אביב",
    description: "חרצית גינה קטנה ועדינה בלבן ורוד. מצוינת לשטיחים ולשולי גינה.",
  },
  {
    id: 155,
    nameHe: "גאיארדיה",
    nameLatin: "Gaillardia × grandiflora",
    categories: ["winter-annuals", "perennials"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    bloomSeason: "חורף-קיץ",
    description: "פרחים צבעוניים בגוונים אדום-כתום-צהוב. עמיד לחום ולצורת.",
  },
  {
    id: 156,
    nameHe: "אפונת הנוי הרב-שנתית",
    nameLatin: "Lathyrus latifolius",
    categories: ["winter-annuals", "perennials", "climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 1-2 מטר",
    bloomSeason: "חורף-אביב",
    description: "מטפס רב-שנתי עם פרחים ורודים-סגולים לאורך העונה הקרה.",
  },
  {
    id: 157,
    nameHe: "אורה",
    nameLatin: "Ornithogalum umbellatum",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "אביב",
    description: "בצל קטן עם פרחים לבנים כוכביים. גדל בשטיחים ומתאים לנטורליזציה.",
  },
  {
    id: 158,
    nameHe: "כוכב בית לחם",
    nameLatin: "Ornithogalum arabicum",
    categories: ["winter-annuals", "geophytes", "bulbs"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    bloomSeason: "אביב",
    description: "פרחים לבנים גדולים עם לב שחור. מרהיב כפרח חתוך ובגינה.",
  },
  // ---- עונתיים קיץ ----
  {
    id: 159,
    nameHe: "בגוניה שנתית",
    nameLatin: "Begonia semperflorens",
    categories: ["summer-annuals", "annuals"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "צמח עונתי קיץ עם פרחים ורודים-לבנים-אדומים. אוהב חצי-צל בקיץ ישראלי.",
  },
  {
    id: 160,
    nameHe: "אימפטיינס",
    nameLatin: "Impatiens walleriana",
    categories: ["summer-annuals", "annuals", "shade"],
    sun: "shade",
    water: "high",
    height: "0.2-0.6 מטר",
    bloomSeason: "קיץ",
    description: "אחד הצמחים הבודדים שפורחים בצל מלא. פרחים בצבעים רבים לאורך כל הקיץ.",
  },
  {
    id: 161,
    nameHe: "צלוסיה",
    nameLatin: "Celosia argentea",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.3-0.9 מטר",
    bloomSeason: "קיץ",
    description: "פרחים בצורת נוצות או שיבולים בגוונים כתום, ורוד ואדום. דרמטי ומרהיב.",
  },
  {
    id: 162,
    nameHe: "תורניה",
    nameLatin: "Torenia fournieri",
    categories: ["summer-annuals", "annuals", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "קיץ",
    description: "פרחים מפוספסים בגוונים ורוד-סגול. מצוין לגינות צל בקיץ.",
  },
  {
    id: 163,
    nameHe: "ניקוטיאנה",
    nameLatin: "Nicotiana alata",
    categories: ["summer-annuals", "annuals"],
    sun: "partial",
    water: "medium",
    height: "0.6-1.2 מטר",
    bloomSeason: "קיץ",
    description: "צמח ריחני המפיץ ריח נפלא בערב. פרחים לבנים, ורודים ואדומים.",
  },
  {
    id: 164,
    nameHe: "תלטית",
    nameLatin: "Catharanthus roseus",
    categories: ["summer-annuals", "perennials"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "צמח עמיד חום ובצורת. פרחים ורודים-לבנים כל הקיץ. מצוין לגינות ישראליות.",
  },
  {
    id: 165,
    nameHe: "פורטולקה",
    nameLatin: "Portulaca grandiflora",
    categories: ["summer-annuals", "annuals", "succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "קיץ",
    description: "צמח נשפך סוקולנטי עם פרחים צבעוניים הנפתחים בשמש. עמיד בחום ובצורת.",
  },
  {
    id: 166,
    nameHe: "גומפרנה",
    nameLatin: "Gomphrena globosa",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "low",
    height: "0.2-0.6 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "ראשי פרחים כדוריים בורדו-ורודים-לבנים. מצוין כפרח חתוך ויבש.",
  },
  {
    id: 167,
    nameHe: "אנגלוניה",
    nameLatin: "Angelonia angustifolia",
    categories: ["summer-annuals", "perennials"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "פרחים עדינים בגוונים סגול, ורוד ולבן. עמיד לחום ישראלי קיצוני.",
  },
  {
    id: 168,
    nameHe: "היפואסטס",
    nameLatin: "Hypoestes phyllostachya",
    categories: ["summer-annuals", "indoor"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.5 מטר",
    description: "עלים מנוקדים בוורוד על רקע ירוק. גדל כשיח קטן בצל.",
  },
  {
    id: 169,
    nameHe: "קסנתמום",
    nameLatin: "Xeranthemum annuum",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "low",
    height: "0.4-0.6 מטר",
    bloomSeason: "קיץ",
    description: "פרח שנתי יבש-נצחי עם פרחים בסגול ולבן. מצוין לשילובים יבשים.",
  },
  {
    id: 170,
    nameHe: "קוקסקומב",
    nameLatin: "Celosia cristata",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "קיץ",
    description: "פרחים בצורת קרפן-תרנגול בגוונים אדום, ורוד וצהוב. ייחודי ובולט.",
  },
  {
    id: 171,
    nameHe: "טיטוניה",
    nameLatin: "Tithonia rotundifolia",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "חמניות מקסיקאנית עם פרחים כתומים ענקיים. גבוהה, בולטת ומושכת פרפרים.",
  },
  {
    id: 172,
    nameHe: "פלוקס שנתי",
    nameLatin: "Phlox drummondii",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "קיץ",
    description: "פרחים צבעוניים בגוונים ורוד, אדום ולבן עם מרכז בולט. פורח בשפע.",
  },
  {
    id: 173,
    nameHe: "אמרנט",
    nameLatin: "Amaranthus caudatus",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.6-1.5 מטר",
    bloomSeason: "קיץ",
    description: "צמח דרמטי עם אשכולות פרחים ארוכים אדומים תלויים.",
  },
  {
    id: 174,
    nameHe: "אגרטום",
    nameLatin: "Ageratum houstonianum",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.1-0.4 מטר",
    bloomSeason: "קיץ",
    description: "פרחים כחולים-תכלתיים פלואפיים. מצוין לגבולות ולשטיחים קיץ.",
  },
  {
    id: 175,
    nameHe: "קנדיטוף",
    nameLatin: "Iberis umbellata",
    categories: ["summer-annuals", "annuals"],
    sun: "full",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "קיץ",
    description: "אשכולות פרחים לבנים-ורודים-סגולים. פורח בקיץ ומתאים לגבולות.",
  },
  // ---- דקלים ----
  {
    id: 176,
    nameHe: "פניקס קנריים",
    nameLatin: "Phoenix canariensis",
    categories: ["palms", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "10-20 מטר",
    description: "דקל מרשים בעל כתר ירוק ענק ועצום גזע. נפוץ מאוד בנוף הישראלי.",
  },
  {
    id: 177,
    nameHe: "פניקס רואבלני",
    nameLatin: "Phoenix roebelenii",
    categories: ["palms", "ornamental-trees", "indoor"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    description: "דקל קטן ועדין מושלם לעציצים ולגינות קטנות.",
  },
  {
    id: 178,
    nameHe: "ואשינגטוניה",
    nameLatin: "Washingtonia robusta",
    categories: ["palms", "trees"],
    sun: "full",
    water: "low",
    height: "15-25 מטר",
    description: "דקל מקסיקני גבוה עם גזע ישר. נפוץ ברחובות ישראל.",
  },
  {
    id: 179,
    nameHe: "ואשינגטוניה חוטנית",
    nameLatin: "Washingtonia filifera",
    categories: ["palms", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "10-15 מטר",
    description: "דקל מניפה אמריקני עם חוטים תלויים מעלי המניפה. עמיד לקרה יחסית.",
  },
  {
    id: 180,
    nameHe: "ליביסטונה",
    nameLatin: "Livistona chinensis",
    categories: ["palms", "ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "5-15 מטר",
    description: "דקל עם עלים עגולים בצורת מניפה. יפה כדקל גן.",
  },
  {
    id: 181,
    nameHe: "ציקס",
    nameLatin: "Cycas revoluta",
    categories: ["palms", "ornamental-trees", "indoor"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    description: "למרות שמו אינו דקל אמיתי אלא ציקד. גדל לאט מאוד ואורך חייו מאות שנים.",
  },
  {
    id: 182,
    nameHe: "ריפאלפיס",
    nameLatin: "Rhapis excelsa",
    categories: ["palms", "indoor"],
    sun: "partial",
    water: "medium",
    height: "1-3 מטר",
    description: "דקל גמדי מושלם לפנים הבית. עלים ירוקים מבריקים ואלגנטיים.",
  },
  {
    id: 183,
    nameHe: "קמרדוריאה",
    nameLatin: "Chamaedorea elegans",
    categories: ["palms", "indoor"],
    sun: "shade",
    water: "medium",
    height: "0.5-2 מטר",
    description: "דקל גמדי עמיד בצל. הפנים-ביתי הנפוץ ביותר בעולם.",
  },
  {
    id: 184,
    nameHe: "קוקוס",
    nameLatin: "Cocos nucifera",
    categories: ["palms", "fruit-trees"],
    sun: "full",
    water: "high",
    height: "20-30 מטר",
    description: "דקל הקוקוס הטרופי עם פרי הקוקוס המוכר. צריך חום רב ואינו עמיד קור.",
  },
  {
    id: 185,
    nameHe: "ביסמרקיה",
    nameLatin: "Bismarckia nobilis",
    categories: ["palms", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "10-20 מטר",
    description: "דקל מדהים בעל עלי מניפה כחולים-כסופים. מרהיב כנקודת מוקד בגן.",
  },
  {
    id: 186,
    nameHe: "בוטייה",
    nameLatin: "Butia capitata",
    categories: ["palms", "fruit-trees"],
    sun: "full",
    water: "low",
    height: "4-8 מטר",
    description: "דקל ג'לי עם פרי אכיל מתוק-חמצמץ. עמיד בטמפרטורות נמוכות.",
  },
  {
    id: 187,
    nameHe: "ברכאה",
    nameLatin: "Brahea armata",
    categories: ["palms", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "5-12 מטר",
    description: "דקל מניפה מקסיקני עם עלים כחולים-כסופים מדהימים. עמיד בצורת.",
  },
  {
    id: 188,
    nameHe: "פלמה מלכה",
    nameLatin: "Syagrus romanzoffiana",
    categories: ["palms", "ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "8-15 מטר",
    description: "דקל אלגנטי עם כפות ירוקות מרושתות. נפוץ בגנים ישראליים.",
  },
  {
    id: 189,
    nameHe: "תמר דקל",
    nameLatin: "Phoenix dactylifera",
    categories: ["palms", "fruit-trees"],
    sun: "full",
    water: "low",
    height: "15-25 מטר",
    description: "דקל התמרים הנפוץ. ייצרן פרי התמר המוכר. עמיד בצורת ובחום קיצוני.",
  },
  {
    id: 190,
    nameHe: "חמאדוריאה מפוצלת",
    nameLatin: "Chamaedorea seifrizii",
    categories: ["palms", "indoor", "shade"],
    sun: "partial",
    water: "medium",
    height: "1.5-3 מטר",
    description: "דקל גמדי מרובה גבעולים. מושלם לפינות פנים ולמרפסות מוצלות.",
  },
  // ---- עצי גדר חיה ----
  {
    id: 191,
    nameHe: "מורן מבריק",
    nameLatin: "Viburnum lucidum",
    categories: ["hedge-trees", "privacy-shrubs"],
    sun: "partial",
    water: "medium",
    height: "3-6 מטר",
    description: "שיח גדר חיה אייקוני. עלים מבריקים ירוק-כהים ופרחים לבנים. צמיחה מהירה ומסך מצוין.",
  },
  {
    id: 192,
    nameHe: "פיטוספורום גדר",
    nameLatin: "Pittosporum tobira",
    categories: ["hedge-trees", "privacy-shrubs"],
    sun: "partial",
    water: "low",
    height: "2-4 מטר",
    description: "שיח גדר נפוץ עם עלים כהים ופרחים לבנים ריחניים. עמיד בצורת.",
  },
  {
    id: 193,
    nameHe: "ליגוסטרום גדר",
    nameLatin: "Ligustrum japonicum",
    categories: ["hedge-trees", "privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    description: "עץ גדר קלאסי. גדל מהר ומחזיק עיצוב גיזום. עלים ירוק-כהים מבריקים.",
  },
  {
    id: 194,
    nameHe: "פוטיניה אדומה",
    nameLatin: "Photinia × fraseri",
    categories: ["hedge-trees", "privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    description: "גדר חיה עם עלים חדשים בצבע אדום בולט. צבעוני ואטרקטיבי.",
  },
  {
    id: 195,
    nameHe: "ארבוריטה",
    nameLatin: "Thuja occidentalis",
    categories: ["hedge-trees", "trees"],
    sun: "full",
    water: "medium",
    height: "5-15 מטר",
    description: "ברוש מערבי בעל עלים קשקשיים. גדר חיה פופולרית ומסך גבוה.",
  },
  {
    id: 196,
    nameHe: "לאורוס",
    nameLatin: "Laurus nobilis",
    categories: ["hedge-trees", "herbs", "shrubs"],
    sun: "full",
    water: "low",
    height: "3-8 מטר",
    description: "עץ הדפנה - עלים ריחניים לבישול. גם גדר חיה יפה וגם תבלין.",
  },
  {
    id: 197,
    nameHe: "אלת המסטיק",
    nameLatin: "Pistacia lentiscus",
    categories: ["hedge-trees", "mediterranean", "shrubs"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    description: "שיח ים-תיכוני מובהק. עמיד בצורת ובחום. מסך ירוק נצחי.",
  },
  {
    id: 198,
    nameHe: "ברברייה",
    nameLatin: "Berberis thunbergii",
    categories: ["hedge-trees", "shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    description: "שיח קוצני עם עלים אדומים מרהיבים. מצוין כגדר מאבטחת.",
  },
  {
    id: 199,
    nameHe: "לוניצרה",
    nameLatin: "Lonicera nitida",
    categories: ["hedge-trees", "privacy-shrubs"],
    sun: "partial",
    water: "medium",
    height: "1-2 מטר",
    description: "שיח עלים קטנים צפוף. מושלם לגידור נמוך ועיצוב טופיארי.",
  },
  {
    id: 200,
    nameHe: "אספרגוס נוי",
    nameLatin: "Asparagus densiflorus",
    categories: ["hedge-trees", "perennials", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.5-1 מטר",
    description: "צמח שרכי מאופיין בעלים עדינים כמחטים. יפה כגבול או כשיח קרקע.",
  },
  {
    id: 201,
    nameHe: "דודונאה",
    nameLatin: "Dodonaea viscosa",
    categories: ["hedge-trees", "shrubs", "mediterranean"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    description: "שיח מהיר גידול ועמיד בצורת. מצוין לגדרות בגינות יבשות.",
  },
  {
    id: 202,
    nameHe: "אקליפטוס גמדי",
    nameLatin: "Eucalyptus torquata",
    categories: ["hedge-trees", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "5-8 מטר",
    description: "אקליפטוס גמדי יחסית עם פרחים ורודים יפים. מצוין כמסך.",
  },
  {
    id: 203,
    nameHe: "רוזמרין גבוה",
    nameLatin: "Rosmarinus officinalis 'Tuscan Blue'",
    categories: ["hedge-trees", "herbs", "shrubs"],
    sun: "full",
    water: "low",
    height: "1.5-2 מטר",
    description: "רוזמרין זקוף וגבוה המתאים כגדר ריחנית. פרחים כחולים ועלים ריחניים.",
  },
  {
    id: 204,
    nameHe: "קרפוברוטוס",
    nameLatin: "Carpobrotus edulis",
    categories: ["hedge-trees", "succulents", "trailing"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    description: "צמח מכסה קרקע בשרני עם פרחים סגולים-צהובים. עמיד בקרקעות מלוחות.",
  },
  {
    id: 205,
    nameHe: "זית ארבקינה",
    nameLatin: "Olea europaea 'Arbequina'",
    categories: ["hedge-trees", "fruit-trees"],
    sun: "full",
    water: "low",
    height: "2-4 מטר",
    description: "זית גמדי מושלם לעציצים ולגדרות נמוכות. מניב זיתים קטנים בשפע.",
  },
  // ---- ורדים ----
  {
    id: 206,
    nameHe: "ורד היברידי",
    nameLatin: "Rosa × hybrida",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.5-1.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד הגן הקלאסי. קיים במאות זנים וצבעים. מלך הגן הישראלי.",
    tips: "גזום חזק בסוף הקיץ לפריחת סתיו.",
  },
  {
    id: 207,
    nameHe: "ורד מטפס",
    nameLatin: "Rosa climber",
    categories: ["roses", "climbers"],
    sun: "full",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "אביב-קיץ",
    description: "ורד מטפס על גדרות וקשתות. יוצר מפל של פרחים ריחניים.",
  },
  {
    id: 208,
    nameHe: "ורד מיניאטורי",
    nameLatin: "Rosa minima",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד גמדי מושלם לעציצים ולגינת כיס. כל פרטי הורד בגרסה קטנה.",
  },
  {
    id: 209,
    nameHe: "ורד דמשק",
    nameLatin: "Rosa × damascena",
    categories: ["roses", "shrubs", "herbs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "אביב",
    description: "ורד הדמשק - ריחני ביותר. בסיס לשמן ורדים יקר. עלי כותרת אכילים.",
  },
  {
    id: 210,
    nameHe: "ורד שרביטן",
    nameLatin: "Rosa rugosa",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "ורד עמיד ועם פרחים ורודים-סגולים ריחניים. פרי אדום גדול (ורד ים).",
  },
  {
    id: 211,
    nameHe: "ורד בנקסיה",
    nameLatin: "Rosa banksiae",
    categories: ["roses", "climbers"],
    sun: "full",
    water: "low",
    height: "מטפס 4-8 מטר",
    bloomSeason: "אביב",
    description: "ורד מטפס בלתי קוצני עם אשכולות פרחים צהובים או לבנים קטנים.",
  },
  {
    id: 212,
    nameHe: "ורד מוס",
    nameLatin: "Rosa centifolia",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1-1.5 מטר",
    bloomSeason: "אביב",
    description: "ורד עתיק עם פרחים כדוריים צפופים ריחניים מאוד. צבע ורוד עמוק.",
  },
  {
    id: 213,
    nameHe: "ורד אוסטין",
    nameLatin: "Rosa × 'David Austin'",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.8-1.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורדי אוסטין - שילוב מושלם בין יופי עתיק לעמידות מודרנית.",
  },
  {
    id: 214,
    nameHe: "ורד פלורינדה",
    nameLatin: "Rosa floribunda",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.6-1.2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד פורח בשפע עם אשכולות פרחים. פחות עצום אך יותר צבעוני.",
  },
  {
    id: 215,
    nameHe: "ורד גרנדיפלורה",
    nameLatin: "Rosa grandiflora",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד גדול-פרח משלב מאפייני הורד ההיברידי עם שפע הפריחה של הפלורינדה.",
  },
  {
    id: 216,
    nameHe: "ורד שלום",
    nameLatin: "Rosa 'Peace'",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1-1.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד 'שלום' - הורד המפורסם ביותר בעולם. פרחים ורוד-צהוב ריחניים.",
  },
  {
    id: 217,
    nameHe: "ורד ניו דאון",
    nameLatin: "Rosa 'New Dawn'",
    categories: ["roses", "climbers"],
    sun: "full",
    water: "medium",
    height: "4-6 מטר",
    bloomSeason: "קיץ",
    description: "ורד מטפס ורוד-עדין עם פרחים ריחניים. גדל מהר ומכסה גדרות וקשתות.",
  },
  {
    id: 218,
    nameHe: "ורד אייסברג",
    nameLatin: "Rosa 'Iceberg'",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.8-1.2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד לבן אייקוני - אחד הנפוצים בישראל. פורח ברצף כמעט כל השנה.",
  },
  {
    id: 219,
    nameHe: "ורד מר. לינקולן",
    nameLatin: "Rosa 'Mr. Lincoln'",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1-1.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד היברידי אדום עמוק עם ריח עז וקלאסי. אחד הורדים האדומים המפורסמים.",
  },
  {
    id: 220,
    nameHe: "ורד מלכה אליזבת",
    nameLatin: "Rosa × 'Queen Elizabeth'",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1.5-2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד גרנדיפלורה ורוד אלגנטי. פורח בשפע ועמיד למחלות.",
  },
  {
    id: 221,
    nameHe: "ורד שיחי מודרני",
    nameLatin: "Rosa shrub modern",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד שיחי מודרני עמיד למחלות עם פריחה חוזרת לאורך העונה.",
  },
  {
    id: 222,
    nameHe: "ורד קנדי",
    nameLatin: "Rosa 'Canadian'",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "קיץ",
    description: "ורד קנדי עמיד קור ומחלות. פורח בקיץ בפרחים ורודים-אדומים.",
  },
  {
    id: 223,
    nameHe: "ורד פטיו",
    nameLatin: "Rosa patio",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד קומפקטי מושלם לעציצים ולמרפסות. פורח בצבעים מגוונים לאורך העונה.",
  },
  {
    id: 224,
    nameHe: "ורד שטיח",
    nameLatin: "Rosa 'Flower Carpet'",
    categories: ["roses", "shrubs", "trailing"],
    sun: "full",
    water: "low",
    height: "0.6-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד שטיח - מכסה שטחים גדולים בפרחים רבים. מינימום טיפול.",
  },
  {
    id: 225,
    nameHe: "ורד נוסטלגי",
    nameLatin: "Rosa nostalgic",
    categories: ["roses", "shrubs"],
    sun: "full",
    water: "medium",
    height: "0.8-1.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ורד בסגנון עתיק עם פרחים גדולים ורחבים וריח קלאסי. אלגנטי ומרשים.",
  },
  // ---- הדסים ----
  {
    id: 226,
    nameHe: "הדס רגיל",
    nameLatin: "Myrtus communis",
    categories: ["myrtles", "shrubs", "mediterranean", "herbs"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "הדס ים-תיכוני קלאסי עם עלים ריחניים ופרחים לבנים קטנים. קדוש בתרבות היהודית.",
  },
  {
    id: 227,
    nameHe: "הדס גמדי",
    nameLatin: "Myrtus communis 'Compacta'",
    categories: ["myrtles", "shrubs"],
    sun: "full",
    water: "low",
    height: "0.5-1 מטר",
    bloomSeason: "קיץ",
    description: "הדס גמדי מושלם לגידור נמוך ולעציצים.",
  },
  {
    id: 228,
    nameHe: "קליסטמון",
    nameLatin: "Callistemon citrinus",
    categories: ["myrtles", "shrubs", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "2-4 מטר",
    bloomSeason: "קיץ",
    description: "בקבוקן אדום - פרחים ייחודיים בצורת מברשת בקבוק. עמיד ואטרקטיבי.",
  },
  {
    id: 229,
    nameHe: "לפטוספרמום",
    nameLatin: "Leptospermum scoparium",
    categories: ["myrtles", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "אביב",
    description: "שיח ניו-זילנדי עם פרחים קטנים ורודים-לבנים בשפע רב.",
  },
  {
    id: 230,
    nameHe: "אוגניה",
    nameLatin: "Eugenia uniflora",
    categories: ["myrtles", "fruit-trees", "hedge-trees"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    bloomSeason: "קיץ",
    description: "עץ פרי טרופי עם פרי אדום-כתום טעים. גם גדר חיה יפה.",
  },
  {
    id: 231,
    nameHe: "מלאלוקה",
    nameLatin: "Melaleuca alternifolia",
    categories: ["myrtles", "shrubs", "herbs"],
    sun: "full",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "עץ טי-טרי. עלים ריחניים עם שמן אתרי בעל סגולות רפואיות.",
  },
  {
    id: 232,
    nameHe: "פייחוא",
    nameLatin: "Feijoa sellowiana",
    categories: ["myrtles", "fruit-trees", "shrubs"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    bloomSeason: "קיץ",
    description: "פרי פייחואה - פרי ירוק עם בשר לבן ריחני. גם שיח נוי יפה.",
  },
  {
    id: 233,
    nameHe: "בופורטיה",
    nameLatin: "Beaufortia sparsa",
    categories: ["myrtles", "shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח אוסטרלי עם פרחים כתומים-אדומים ייחודיים בצורת מברשת. עמיד בצורת.",
  },
  {
    id: 234,
    nameHe: "גויאבה תותית",
    nameLatin: "Psidium cattleianum",
    categories: ["myrtles", "fruit-trees"],
    sun: "full",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "גויאבה תותית - פרי אדום קטן ומתוק. שיח נאה עם עלים מבריקים.",
  },
  {
    id: 235,
    nameHe: "אגוניס",
    nameLatin: "Agonis flexuosa",
    categories: ["myrtles", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "5-10 מטר",
    description: "עץ פפרמינט אוסטרלי. עלים ריחניים ואלגנטיים התלויים בענפים גמישים.",
  },
  // ---- קונוולריים ----
  {
    id: 236,
    nameHe: "כרך סגול",
    nameLatin: "Ipomoea purpurea",
    categories: ["convolvulaceae", "climbers", "summer-annuals"],
    sun: "full",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "מטפס שנתי מהיר עם פרחים גדולים בגוונים סגול, ורוד ולבן.",
  },
  {
    id: 237,
    nameHe: "כרך כחול",
    nameLatin: "Ipomoea indica",
    categories: ["convolvulaceae", "climbers", "perennials"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "מטפס רב-שנתי עם פרחים כחולים-סגולים גדולים. פורח בשפע.",
  },
  {
    id: 238,
    nameHe: "כרך לבן",
    nameLatin: "Ipomoea alba",
    categories: ["convolvulaceae", "climbers"],
    sun: "full",
    water: "medium",
    height: "5-10 מטר",
    bloomSeason: "קיץ",
    description: "פרח הירח - פרחים לבנים גדולים הנפתחים בלילה. ריח עדין ומיוחד.",
  },
  {
    id: 239,
    nameHe: "בטטה קישוטית",
    nameLatin: "Ipomoea batatas",
    categories: ["convolvulaceae", "trailing", "fruit-trees"],
    sun: "full",
    water: "medium",
    height: "מטפס/נשפך 1-3 מטר",
    description: "בטטה - גידולת עם עלים אדמדמים קישוטיים ופקעות אכילות.",
  },
  {
    id: 240,
    nameHe: "קליסטגיה",
    nameLatin: "Calystegia sepium",
    categories: ["convolvulaceae", "climbers", "perennials"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "מטפס רב-שנתי עם פרחים לבנים-ורודים גדולים. גדל בצמחיה טבעית.",
  },
  {
    id: 241,
    nameHe: "חלבלוב שלושה-צבעים",
    nameLatin: "Convolvulus tricolor",
    categories: ["convolvulaceae", "annuals", "trailing"],
    sun: "full",
    water: "low",
    height: "0.3-0.5 מטר",
    bloomSeason: "קיץ",
    description: "חלבלוב שלושה-צבעים. פרחים כחולים עם לב לבן-צהוב. יפה מאוד.",
  },
  {
    id: 242,
    nameHe: "חלבלוב כחול",
    nameLatin: "Convolvulus sabatius",
    categories: ["convolvulaceae", "perennials", "trailing"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שטיח כחול עדין עמיד בצורת. מושלם לאדניות ולמדרונות.",
  },
  {
    id: 243,
    nameHe: "חלבלוב כסוף",
    nameLatin: "Convolvulus cneorum",
    categories: ["convolvulaceae", "shrubs", "mediterranean"],
    sun: "full",
    water: "low",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח עם עלים כסופים ופרחים לבנים. עמיד בצורת ובחום.",
  },
  {
    id: 244,
    nameHe: "מאורנדלה",
    nameLatin: "Maurandella antirrhiniflora",
    categories: ["convolvulaceae", "climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 1-3 מטר",
    bloomSeason: "קיץ",
    description: "מטפס עדין עם פרחים בסגול ולבן הדומים לארנבנית. יפה על גדרות וסורגים.",
  },
  {
    id: 245,
    nameHe: "מינה לובטה",
    nameLatin: "Mina lobata",
    categories: ["convolvulaceae", "climbers", "summer-annuals"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "מטפס שנתי עם אשכולות פרחים שמשנים צבע מאדום לכתום לצהוב-לבן.",
  },
  // ---- דגני נוי ----
  {
    id: 246,
    nameHe: "פנניסטום",
    nameLatin: "Pennisetum setaceum",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "0.5-1.5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "דגן מזרקה אדמדם. שיבולות צמריות ורדות-בורדו. עמיד ואטרקטיבי.",
  },
  {
    id: 247,
    nameHe: "פנניסטום לבן",
    nameLatin: "Pennisetum villosum",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "דגן עם שיבולות לבנות-צמריות רכות. נשא ברוח ומעניק תנועה לגינה.",
  },
  {
    id: 248,
    nameHe: "מישקנטוס",
    nameLatin: "Miscanthus sinensis",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "דגן נוי ענק עם שיבולות גדולות. יוצר אפקט וילון צמחי דרמטי.",
  },
  {
    id: 249,
    nameHe: "קורטדריה",
    nameLatin: "Cortaderia selloana",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "2-3 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "דגן הפמפס - שיבולות לבנות-כסופות ענקיות. נקודת מוקד בגן.",
  },
  {
    id: 250,
    nameHe: "פסטוקה כחולה",
    nameLatin: "Festuca glauca",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "0.2-0.4 מטר",
    description: "דגן כחול-כסוף גמדי. מצוין לרצועות ולגינות סלע.",
  },
  {
    id: 251,
    nameHe: "קרקס",
    nameLatin: "Carex oshimensis",
    categories: ["ornamental-grasses", "perennials", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.3-0.6 מטר",
    description: "גמד-קנה ים-תיכוני עם עלים זהובים-ירוקים. יפה בצל.",
  },
  {
    id: 252,
    nameHe: "סטיפה",
    nameLatin: "Stipa tenuissima",
    categories: ["ornamental-grasses", "perennials", "mediterranean"],
    sun: "full",
    water: "low",
    height: "0.4-0.7 מטר",
    description: "דגן עדין המרשרש ברוח. יוצר אפקט קסום של תנועה בגן.",
  },
  {
    id: 253,
    nameHe: "מולנברגיה",
    nameLatin: "Muhlenbergia capillaris",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "0.6-1 מטר",
    bloomSeason: "סתיו",
    description: "דגן ורדרד-ורוד נפלא בסתיו. ענן ורוד קסום.",
  },
  {
    id: 254,
    nameHe: "בוטלואה",
    nameLatin: "Bouteloua gracilis",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "0.3-0.5 מטר",
    description: "דגן מדבר צפון-אמריקאי עמיד לצורת. שיבולות בצורת דגל קטן ייחודיות.",
  },
  {
    id: 255,
    nameHe: "אנדרופוגון",
    nameLatin: "Andropogon gerardii",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "קיץ",
    description: "דגן פרירי גדול עם שיבולות כסופות. צבעוני בסתיו בגוונים כתום-אדום.",
  },
  {
    id: 256,
    nameHe: "פניקום",
    nameLatin: "Panicum virgatum",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "low",
    height: "0.6-1.5 מטר",
    bloomSeason: "קיץ",
    description: "דגן אמריקאי זקוף עם שיבולות מרחפות. יפה מאוד בשמש עת הצהריים.",
  },
  {
    id: 257,
    nameHe: "קלמגרוסטיס",
    nameLatin: "Calamagrostis × acutiflora",
    categories: ["ornamental-grasses", "perennials"],
    sun: "full",
    water: "medium",
    height: "1-1.5 מטר",
    bloomSeason: "קיץ",
    description: "דגן זקוף ואלגנטי. שיבולות ורדרדות קיץ, חומות חורף. ארבעה עונות.",
  },
  {
    id: 258,
    nameHe: "בראכיפודיום",
    nameLatin: "Brachypodium retusum",
    categories: ["ornamental-grasses", "perennials", "mediterranean"],
    sun: "full",
    water: "low",
    height: "0.3-0.5 מטר",
    description: "דגן ים-תיכוני עמיד. מכסה קרקע טבעי ויפה.",
  },
  {
    id: 259,
    nameHe: "ציפרוס",
    nameLatin: "Cyperus alternifolius",
    categories: ["ornamental-grasses", "aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "0.5-1.5 מטר",
    description: "ציפרוס - דמוי פאפירוס עם עלים כמטריה. אוהב מים ואדמה לחה.",
  },
  {
    id: 260,
    nameHe: "פאפירוס",
    nameLatin: "Cyperus papyrus",
    categories: ["ornamental-grasses", "aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "1.5-3 מטר",
    description: "הפאפירוס המצרי האמיתי. גבעולים גבוהים עם ראשי שיבולת עגולים.",
  },
  {
    id: 261,
    nameHe: "קנה",
    nameLatin: "Arundo donax",
    categories: ["ornamental-grasses", "trees", "perennials"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    description: "קנה ענק ישראלי. גדל מהר ויוצר מסך גבוה טבעי. גם ורסיה צבעונית.",
  },
  {
    id: 262,
    nameHe: "פלריס",
    nameLatin: "Phalaris arundinacea 'Picta'",
    categories: ["ornamental-grasses", "perennials"],
    sun: "partial",
    water: "medium",
    height: "0.5-1.5 מטר",
    description: "דגן מפוספס לבן-ירוק. אלגנטי ביותר לשולי גינה.",
  },
  // ---- ים-תיכוניים ----
  {
    id: 263,
    nameHe: "זוטא",
    nameLatin: "Micromeria fruticosa",
    categories: ["mediterranean", "herbs"],
    sun: "full",
    water: "low",
    height: "0.3-0.8 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול ים-תיכוני ריחני. נפוץ בהרי ישראל ומשמש לתה צמחים.",
  },
  {
    id: 264,
    nameHe: "גפרנית",
    nameLatin: "Phagnalon rupestre",
    categories: ["mediterranean", "perennials"],
    sun: "full",
    water: "low",
    height: "0.2-0.4 מטר",
    description: "שיח קטן ים-תיכוני עם עלים לבנים-כסופים. גדל בסדקי סלע.",
  },
  {
    id: 265,
    nameHe: "שנאן",
    nameLatin: "Echinops viscosus",
    categories: ["mediterranean", "perennials"],
    sun: "full",
    water: "low",
    height: "0.5-1 מטר",
    bloomSeason: "קיץ",
    description: "כדור שדה ים-תיכוני עם ראשי פרחים כחולים כדוריים. מושך דבורים.",
  },
  {
    id: 266,
    nameHe: "קורנית",
    nameLatin: "Origanum syriacum",
    categories: ["mediterranean", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-1 מטר",
    bloomSeason: "קיץ",
    description: "הזעתר הסורי האמיתי. תבלין אייקוני בבישול ים-תיכוני. ריחני מאוד.",
  },
  {
    id: 267,
    nameHe: "אזוב",
    nameLatin: "Satureja thymbra",
    categories: ["mediterranean", "herbs"],
    sun: "full",
    water: "low",
    height: "0.2-0.5 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול ים-תיכוני בעל ריח חד וארומטי. גדל בר בהרי ישראל.",
  },
  {
    id: 268,
    nameHe: "שושן חורף",
    nameLatin: "Sternbergia lutea",
    categories: ["mediterranean", "geophytes", "bulbs"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "סתיו",
    description: "פרח בצל ים-תיכוני עם פרחים צהובים בסתיו. פורח בהפתעה לפני הגשמים.",
  },
  {
    id: 269,
    nameHe: "כליל החורש",
    nameLatin: "Cercis siliquastrum",
    categories: ["mediterranean", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "5-10 מטר",
    bloomSeason: "אביב",
    description: "עץ יהודה - עץ ים-תיכוני יפה הפורח ורוד לפני הצצת עלים.",
  },
  {
    id: 270,
    nameHe: "שיטה צהובה",
    nameLatin: "Acacia saligna",
    categories: ["mediterranean", "ornamental-trees", "trees"],
    sun: "full",
    water: "low",
    height: "4-8 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח/עץ עם כדורים צהובים ריחניים בחורף. גדל מהיר ועמיד בצורת.",
  },
  {
    id: 271,
    nameHe: "חרצית כסף",
    nameLatin: "Helichrysum italicum",
    categories: ["mediterranean", "herbs", "perennials"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "חרצית כסף - עלים כסופים ריחניים. פרחים צהובים לא נובלים.",
  },
  {
    id: 272,
    nameHe: "מרווה ים-תיכונית",
    nameLatin: "Salvia fruticosa",
    categories: ["mediterranean", "herbs", "shrubs"],
    sun: "full",
    water: "low",
    height: "0.5-1.5 מטר",
    bloomSeason: "אביב",
    description: "מרווה ים-תיכונית ישראלית. עמידה בצורת ובחום. ריחנית ואטרקטיבית.",
  },
  {
    id: 273,
    nameHe: "ציסטוס",
    nameLatin: "Cistus × purpureus",
    categories: ["mediterranean", "shrubs"],
    sun: "full",
    water: "low",
    height: "0.8-1.5 מטר",
    bloomSeason: "אביב",
    description: "ציסטוס - שיח ים-תיכוני עמיד עם פרחים גדולים ורודים-סגולים.",
  },
  {
    id: 274,
    nameHe: "אסטרגלוס",
    nameLatin: "Astragalus boeticus",
    categories: ["mediterranean", "perennials"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    description: "קטנית ים-תיכונית עם פרחים סגולים-ורודים קטנים. מקבע חנקן באדמה.",
  },
  {
    id: 275,
    nameHe: "קנוקרפוס",
    nameLatin: "Conocarpus erectus",
    categories: ["mediterranean", "hedge-trees", "trees"],
    sun: "full",
    water: "low",
    height: "4-8 מטר",
    description: "עץ ים-תיכוני עמיד מאוד בתנאי חוף ומליחות. גדר חיה מצוינת.",
  },
  // ---- שרכים ----
  {
    id: 276,
    nameHe: "שרך חיצי",
    nameLatin: "Nephrolepis exaltata",
    categories: ["ferns", "indoor", "shade"],
    sun: "shade",
    water: "high",
    height: "0.3-0.8 מטר",
    description: "שרך הדום הפנים-ביתי הנפוץ. עלים ארוכים מעוצבים. אוהב לחות.",
  },
  {
    id: 277,
    nameHe: "שרך ירושלמי",
    nameLatin: "Pteris cretica",
    categories: ["ferns", "indoor", "shade"],
    sun: "shade",
    water: "medium",
    height: "0.3-0.6 מטר",
    description: "שרך קטן עם עלים מפוסלים ירוק-לבן. מתאים לעציצים ולגינות צל.",
  },
  {
    id: 278,
    nameHe: "שרך המלך",
    nameLatin: "Osmunda regalis",
    categories: ["ferns", "shade", "aquatic"],
    sun: "shade",
    water: "high",
    height: "0.8-1.5 מטר",
    description: "שרך מפואר גדול עם עלים בצורת נוצה. אוהב לחות ומתאים ליד בריכות.",
  },
  {
    id: 279,
    nameHe: "שרך עץ",
    nameLatin: "Dicksonia antarctica",
    categories: ["ferns", "shade"],
    sun: "shade",
    water: "high",
    height: "1-3 מטר",
    description: "שרך עץ הממשיך להדהים כיום כמו בתקופת הדינוזאורים. גזע ייחודי.",
  },
  {
    id: 280,
    nameHe: "שרך קן הציפור",
    nameLatin: "Asplenium nidus",
    categories: ["ferns", "indoor", "shade"],
    sun: "shade",
    water: "medium",
    height: "0.3-1 מטר",
    description: "שרך קן הציפור - עלים גדולים שלמים ומבריקים. מרהיב כצמח בית.",
  },
  {
    id: 281,
    nameHe: "אדיאנטום",
    nameLatin: "Adiantum capillus-veneris",
    categories: ["ferns", "indoor", "shade"],
    sun: "shade",
    water: "high",
    height: "0.2-0.5 מטר",
    description: "שרך שיער הנימפות - עלים עדינים קטנים. יפה מאוד אך צריך לחות רבה.",
  },
  {
    id: 282,
    nameHe: "בלכנום",
    nameLatin: "Blechnum spicant",
    categories: ["ferns", "shade"],
    sun: "shade",
    water: "high",
    height: "0.3-0.6 מטר",
    description: "שרך עם עלים כהים וזקופים בקשת. אוהב צל ולחות גבוהה.",
  },
  {
    id: 283,
    nameHe: "פוליפודיום",
    nameLatin: "Polypodium vulgare",
    categories: ["ferns", "shade", "perennials"],
    sun: "shade",
    water: "medium",
    height: "0.2-0.4 מטר",
    description: "שרך קטן עמיד הגדל בסדקי סלע ועל גזעי עצים. עלים מחותכים יפהפיים.",
  },
  {
    id: 284,
    nameHe: "דוואליה",
    nameLatin: "Davallia trichomanoides",
    categories: ["ferns", "indoor", "trailing"],
    sun: "partial",
    water: "medium",
    height: "0.3-0.5 מטר",
    description: "שרך ארנבת - שורשים חומים שעירים וחיים הבורחים מהעציץ.",
  },
  {
    id: 285,
    nameHe: "פטרידיום",
    nameLatin: "Pteridium aquilinum",
    categories: ["ferns", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.6-1.5 מטר",
    description: "שרך הנשר - שרך גדול ועמיד המכסה שטחים נרחבים. עמיד בצל חלקי.",
  },
  // ---- צמחי מים ----
  {
    id: 286,
    nameHe: "לוטוס",
    nameLatin: "Nelumbo nucifera",
    categories: ["aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "0.5-1.5 מטר",
    bloomSeason: "קיץ",
    description: "לוטוס קדוש - פרחים ורודים עצומים. סמל הטוהר בתרבויות רבות.",
  },
  {
    id: 287,
    nameHe: "שושנת מים",
    nameLatin: "Nymphaea × hybrida",
    categories: ["aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "צף במים",
    bloomSeason: "קיץ",
    description: "שושנת מים יפהפה. עלים צפים ופרחים לבנים-ורודים-סגולים.",
  },
  {
    id: 288,
    nameHe: "איריס מים",
    nameLatin: "Iris pseudacorus",
    categories: ["aquatic", "geophytes", "perennials"],
    sun: "full",
    water: "high",
    height: "0.6-1 מטר",
    bloomSeason: "אביב-קיץ",
    description: "איריס צהוב הגדל בשוליים של גופי מים. פרחים צהובים בולטים.",
  },
  {
    id: 289,
    nameHe: "קנה ים",
    nameLatin: "Typha latifolia",
    categories: ["aquatic", "perennials", "ornamental-grasses"],
    sun: "full",
    water: "high",
    height: "1-2.5 מטר",
    description: "קנה השוחה הנפוץ עם ראשי נקניקיות חומים. נפוץ ליד גופי מים.",
  },
  {
    id: 290,
    nameHe: "פיקיה",
    nameLatin: "Ficinia nodosa",
    categories: ["aquatic", "ornamental-grasses"],
    sun: "full",
    water: "high",
    height: "0.5-1.2 מטר",
    description: "גומא כדורית - גבעולים עגולים ירוקים עם ראשים כדוריים. יפה לבריכות.",
  },
  {
    id: 291,
    nameHe: "אגמון",
    nameLatin: "Schoenoplectus lacustris",
    categories: ["aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "1-2 מטר",
    description: "גבעולים עגולים ישרים הגדלים במים עמוקים. מאפיין אגמים וביצות.",
  },
  {
    id: 292,
    nameHe: "פונטדריה",
    nameLatin: "Pontederia cordata",
    categories: ["aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "0.5-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח מים עם עלים בצורת לב ואשכולות פרחים כחולים.",
  },
  {
    id: 293,
    nameHe: "קלה",
    nameLatin: "Zantedeschia aethiopica",
    categories: ["aquatic", "geophytes", "perennials"],
    sun: "partial",
    water: "high",
    height: "0.6-1 מטר",
    bloomSeason: "חורף-אביב",
    description: "קלה לבנה - פרחים אייקוניים מהסרטים. אוהב לחות. גם צמח בית.",
  },
  {
    id: 294,
    nameHe: "אליסמה",
    nameLatin: "Alisma plantago-aquatica",
    categories: ["aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "0.3-0.8 מטר",
    description: "צמח מים עם עלים בצורת לשון ופרחים לבנים קטנים. אוהב שוליים רטובים.",
  },
  {
    id: 295,
    nameHe: "הידרוקרית",
    nameLatin: "Hydrocharis morsus-ranae",
    categories: ["aquatic", "perennials"],
    sun: "full",
    water: "high",
    height: "צף במים",
    description: "צמח צף קטן עם עלים עגולים ופרחים לבנים עדינים. נהדר לבריכות קטנות.",
  },
  // ---- בית, מטפסים וצל ----
  {
    id: 296,
    nameHe: "ברומליאד",
    nameLatin: "Guzmania lingulata",
    categories: ["indoor", "perennials"],
    sun: "partial",
    water: "medium",
    height: "0.3-0.5 מטר",
    bloomSeason: "כל השנה",
    description: "ברומליאד צבעוני עם 'כוס' מרכזית שאוחזת מים. פורח שנים.",
  },
  {
    id: 297,
    nameHe: "טרדסקנציה",
    nameLatin: "Tradescantia zebrina",
    categories: ["indoor", "trailing", "shade"],
    sun: "partial",
    water: "medium",
    height: "נשפך",
    description: "צמח מסילות - עלים סגולים-כסופים מבריקים. גדל מהר ויפה.",
  },
  {
    id: 298,
    nameHe: "פיקוס מטפס",
    nameLatin: "Ficus pumila",
    categories: ["climbers", "indoor", "shade"],
    sun: "partial",
    water: "medium",
    height: "מטפס 3-5 מטר",
    description: "פיקוס מטפס - מכסה קירות בעלים קטנים ירוקים. עמיד מאוד.",
  },
  {
    id: 299,
    nameHe: "הדרה",
    nameLatin: "Hedera helix",
    categories: ["climbers", "shade", "trailing"],
    sun: "shade",
    water: "medium",
    height: "מטפס/נשפך 5-10 מטר",
    description: "קיסוס אנגלי - מטפס על קירות וגדרות. מכסה קרקע בצל. נצחי.",
  },
  {
    id: 300,
    nameHe: "בואומונטיה",
    nameLatin: "Beaumontia grandiflora",
    categories: ["climbers", "perennials"],
    sun: "full",
    water: "medium",
    height: "מטפס 5-10 מטר",
    bloomSeason: "קיץ",
    description: "נגארה ענקית - פרחים לבנים טרומפטים ריחניים. מרהיב על קשתות.",
  },
  {
    id: 301,
    nameHe: "סולנום מטפס",
    nameLatin: "Solanum jasminoides",
    categories: ["climbers", "perennials"],
    sun: "full",
    water: "medium",
    height: "מטפס 3-5 מטר",
    bloomSeason: "קיץ",
    description: "מטפס רב-שנתי עם פרחים לבנים-תכולים קטנים בשפע. גדל מהר ומכסה גדרות.",
  },
  {
    id: 302,
    nameHe: "קמפסיס",
    nameLatin: "Campsis radicans",
    categories: ["climbers", "perennials"],
    sun: "full",
    water: "medium",
    height: "מטפס 5-10 מטר",
    bloomSeason: "קיץ",
    description: "נחלת הכרמל - פרחים כתומים-אדומים צינוריים. מושך דבורים וציפורים.",
  },
  {
    id: 303,
    nameHe: "אקטינידיה",
    nameLatin: "Actinidia kolomikta",
    categories: ["climbers", "perennials"],
    sun: "partial",
    water: "medium",
    height: "מטפס 3-5 מטר",
    description: "מטפס נוי עם עלים מנוקדים לבן-ורוד. יפה מאוד בפרגולות.",
  },
  {
    id: 304,
    nameHe: "יסמין גמדי",
    nameLatin: "Jasminum humile",
    categories: ["climbers", "shrubs"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "יסמין שיחי עם פרחים צהובים ריחניים. עמיד לחום ולצורת.",
  },
  {
    id: 305,
    nameHe: "כלנדולה",
    nameLatin: "Calendula officinalis",
    categories: ["winter-annuals", "annuals", "herbs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "חורף-אביב",
    description: "חרצית רפואית - פרחים כתומים-צהובים. עלים ופרחים אכילים ורפואיים.",
  },
  {
    id: 306,
    nameHe: "כרפס גינה",
    nameLatin: "Apium graveolens",
    categories: ["herbs", "summer-annuals"],
    sun: "partial",
    water: "high",
    height: "0.3-0.8 מטר",
    description: "כרפס מפורסם לבישול ולסלט. גדל בתנאי לחות גבוהה.",
  },
  {
    id: 307,
    nameHe: "מלון גינה",
    nameLatin: "Cucumis melo",
    categories: ["fruit-trees", "summer-annuals"],
    sun: "full",
    water: "medium",
    height: "מטפס 1-3 מטר",
    bloomSeason: "קיץ",
    description: "מלון גינה מגדל פרי מתוק בקיץ. מטפס על סורגים ומחייב שמש מלאה.",
  },
  {
    id: 308,
    nameHe: "אטד",
    nameLatin: "Lycium europaeum",
    categories: ["mediterranean", "shrubs", "hedge-trees"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    description: "שיח קוצני ים-תיכוני עמיד מאוד. גדר מאבטחת ומאכילה ציפורים.",
  },
  {
    id: 309,
    nameHe: "שריגית",
    nameLatin: "Scilla autumnalis",
    categories: ["geophytes", "bulbs", "mediterranean"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "סתיו",
    description: "בצל ים-תיכוני קטן עם שיבולת פרחים ורודים-סגולים בסתיו.",
  },
  {
    id: 310,
    nameHe: "שיח אברהם",
    nameLatin: "Vitex agnus-castus",
    categories: ["shrubs", "mediterranean", "herbs"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "שיח אברהם הקדוש - אשכולות פרחים סגולים ריחניים. עמיד בצורת מאוד.",
  },
];
