export type SunLevel = 'full' | 'partial' | 'shade';
export type WaterLevel = 'low' | 'medium' | 'high';

export interface Plant {
  id: number;
  nameHe: string;
  nameLatin: string;
  categories: string[];
  sun: SunLevel;
  water: WaterLevel;
  description: string;
  height?: string;
  bloomSeason?: string;
  tips?: string;
}

export const PLANT_CATEGORIES = [
  { key: "all", label: "הכל", emoji: "🌿" },
  { key: "fruit-trees", label: "עצי פרי", emoji: "🍎" },
  { key: "citrus", label: "הדרים", emoji: "🍊" },
  { key: "ornamental-trees", label: "עצי נוי", emoji: "🌳" },
  { key: "trees", label: "עצים", emoji: "🌲" },
  { key: "shrubs", label: "שיחים", emoji: "🌿" },
  { key: "privacy-shrubs", label: "שיחי הסתרה", emoji: "🏡" },
  { key: "perennials", label: "רב שנתיים", emoji: "🌸" },
  { key: "annuals", label: "עונתיים", emoji: "🌻" },
  { key: "indoor", label: "צמחיה לבית", emoji: "🪴" },
  { key: "succulents", label: "סוקולנטים", emoji: "🌵" },
  { key: "cacti", label: "קקטוסים", emoji: "🌵" },
  { key: "trailing", label: "צמחיה נשפכת", emoji: "🍃" },
  { key: "shade", label: "צמחייה לצל", emoji: "🌑" },
  { key: "geophytes", label: "גיאופיטים", emoji: "🌷" },
  { key: "herbs", label: "עשבי תיבול", emoji: "🌱" },
  { key: "climbers", label: "מטפסים", emoji: "🌿" },
];

export function plantImageUrl(plant: Plant): string {
  const genus = plant.nameLatin.split(' ')[0].toLowerCase();
  return `https://source.unsplash.com/400x300/?${encodeURIComponent(genus)},plant&sig=${plant.id}`;
}

export const PLANTS: Plant[] = [
  // ---- עצי פרי ----
  {
    id: 1,
    nameHe: "תפוח",
    nameLatin: "Malus domestica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "אביב",
    description: "עץ פרי נשיר הנפוץ בגינות ישראל. מניב פירות בסתיו ודורש קרה חורפית.",
    tips: "גזום בסוף החורף לתפוקה מרבית.",
  },
  {
    id: 2,
    nameHe: "אגס",
    nameLatin: "Pyrus communis",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "4-7 מטר",
    bloomSeason: "אביב",
    description: "עץ פרי נשיר עם פרחים לבנים יפים באביב. מניב פירות מתוקים בסתיו.",
    tips: "השקה סדירה בקיץ חיונית להבשלת הפרי.",
  },
  {
    id: 3,
    nameHe: "שקד",
    nameLatin: "Prunus dulcis",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "3-8 מטר",
    bloomSeason: "ינואר-פברואר",
    description: "עץ פרי ים-תיכוני הפורח בחורף בפרחים לבנים-ורודים לפני הצצת העלים.",
    tips: "עמיד בצורת ואינו צורך השקיה רבה לאחר הביסוס.",
  },
  {
    id: 4,
    nameHe: "זית",
    nameLatin: "Olea europaea",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "3-10 מטר",
    bloomSeason: "אביב",
    description: "עץ ים-תיכוני עמיד בצורת ועץ פרי חשוב. אורך חיים של מאות שנים.",
    tips: "גזום בתחילת האביב לשמירת צורה ועידוד פריחה.",
  },
  {
    id: 5,
    nameHe: "תאנה",
    nameLatin: "Ficus carica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "קיץ",
    description: "עץ פרי ים-תיכוני עתיק עם עלים גדולים מאוצבעים. פרי מתוק בקיץ ובסתיו.",
    tips: "גזום את הענפים החלשים בחורף לחיזוק הפרי.",
  },
  {
    id: 6,
    nameHe: "רימון",
    nameLatin: "Punica granatum",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "שיח/עץ נוי ופרי. פרחים כתומים בולטים ופרי אדום עשיר בנוגדי חמצון.",
    tips: "עמיד מאוד לחום ולצורת, מתאים לגינה ים-תיכונית.",
  },
  {
    id: 7,
    nameHe: "אפרסק",
    nameLatin: "Prunus persica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    bloomSeason: "פברואר-מרץ",
    description: "עץ פרי נשיר עם פרחים ורודים יפהפיים. מניב פירות בקיץ.",
    tips: "דרושה קרה חורפית מספקת להבטחת יבול טוב.",
  },
  {
    id: 8,
    nameHe: "משמש",
    nameLatin: "Prunus armeniaca",
    categories: ["fruit-trees"],
    sun: "full",
    water: "low",
    height: "3-6 מטר",
    bloomSeason: "ינואר-פברואר",
    description: "עץ פרי מוקדם הפורח בחורף. פרי כתום מתוק בתחילת הקיץ.",
    tips: "פורח מוקדם — הגן מפני כפור.",
  },
  {
    id: 9,
    nameHe: "שזיף",
    nameLatin: "Prunus domestica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "אביב",
    description: "עץ פרי נשיר עם פרי סגול-אדום עסיסי. פורח לבן באביב.",
    tips: "השקה סדירה בתקופת התפתחות הפרי חיונית.",
  },
  {
    id: 10,
    nameHe: "אבוקדו",
    nameLatin: "Persea americana",
    categories: ["fruit-trees"],
    sun: "full",
    water: "high",
    height: "5-10 מטר",
    bloomSeason: "חורף-אביב",
    description: "עץ טרופי בעל עלים ירוקים גדולים ופרי שמני. צריך הגנה מקרה.",
    tips: "הגן מפני קרה וריחות חזקים שעשויים לפגוע בעץ.",
  },
  {
    id: 11,
    nameHe: "מנגו",
    nameLatin: "Mangifera indica",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "4-10 מטר",
    bloomSeason: "חורף",
    description: "עץ טרופי גדול עם עלים ארוכים ופרי מתוק. אוהב חום ולחות.",
    tips: "דורש קיץ חם ולח להבשלת פרי איכותי.",
  },
  {
    id: 12,
    nameHe: "ענבים",
    nameLatin: "Vitis vinifera",
    categories: ["fruit-trees", "climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 5-15 מטר",
    bloomSeason: "אביב",
    description: "גפן נשירה הנותנת פרי עסיסי ומגוון. מתאימה לפרגולות ולגידול על גדרות.",
    tips: "גיזום חורפי נמרץ חיוני לתפוקה גבוהה.",
  },
  {
    id: 13,
    nameHe: "תמר",
    nameLatin: "Phoenix dactylifera",
    categories: ["fruit-trees", "ornamental-trees"],
    sun: "full",
    water: "low",
    height: "10-25 מטר",
    bloomSeason: "אביב",
    description: "דקל אייקוני של המזרח התיכון. נותן פרי מתוק ומשמש כעץ נוי מרשים.",
    tips: "עמיד לחום ולצורת — אחד העצים הסבלניים ביותר.",
  },
  {
    id: 14,
    nameHe: "גויאבה",
    nameLatin: "Psidium guajava",
    categories: ["fruit-trees"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "קיץ",
    description: "עץ טרופי עם פרי בעל ניחוח ייחודי. עלים ירוקים כהים ופרי לבן/ורוד.",
    tips: "מתאים לאזורים חמים ועמיד למחלות.",
  },
  {
    id: 15,
    nameHe: "קיווי",
    nameLatin: "Actinidia deliciosa",
    categories: ["fruit-trees", "climbers"],
    sun: "partial",
    water: "high",
    height: "מטפס",
    bloomSeason: "אביב",
    description: "גפן נמרצת הנושאת פרי עשיר בוויטמין C. צריכה תמיכה ומבנה לטיפוס.",
    tips: "נדרשים זכר ונקבה לפרייה, ודרושה קרה חורפית.",
  },
  // ---- הדרים ----
  {
    id: 16,
    nameHe: "לימון",
    nameLatin: "Citrus limon",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "כל השנה",
    description: "הדר פורה ועמיד הנותן פרי כמעט כל השנה. פרחים ריחניים לבנים.",
    tips: "דשן בחנקן מספר פעמים בשנה לפריחה ופריה רצופה.",
  },
  {
    id: 17,
    nameHe: "תפוז",
    nameLatin: "Citrus sinensis",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "3-5 מטר",
    bloomSeason: "אביב",
    description: "הדר קלאסי עם פרחים ריחניים מאוד ופרי מתוק. עץ נוי ופרי כאחד.",
    tips: "הגן מפני קרה חזקה מתחת ל-3 מעלות.",
  },
  {
    id: 18,
    nameHe: "מנדרינה",
    nameLatin: "Citrus reticulata",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "אביב",
    description: "הדר קומפקטי עם פרי מתוק וקל לקילוף. עץ גינה אהוב למשפחות.",
    tips: "מתאים לגידול בעציץ גדול על מרפסת.",
  },
  {
    id: 19,
    nameHe: "אשכולית",
    nameLatin: "Citrus paradisi",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "3-6 מטר",
    bloomSeason: "אביב",
    description: "הדר גדול עם פרי מריר-מתוק ועשיר בוויטמין C. עץ גדול ורחב כתר.",
    tips: "צריך חום רב להבשלת פרי מתוק.",
  },
  {
    id: 20,
    nameHe: "ליים",
    nameLatin: "Citrus aurantiifolia",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "כל השנה",
    description: "הדר טרופי עם פרי ירוק חמצמץ. פורח כמעט כל השנה.",
    tips: "רגיש לקרה — שמור בסביבה מוגנת בחורף.",
  },
  {
    id: 21,
    nameHe: "פומלה",
    nameLatin: "Citrus maxima",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "4-8 מטר",
    bloomSeason: "אביב",
    description: "ההדר הגדול בעולם עם פרי ענקי מתוק ועסיסי. עץ נוי מרשים.",
    tips: "דרוש שטח גדול — עץ מרשים ובולט.",
  },
  {
    id: 22,
    nameHe: "קלמנטינה",
    nameLatin: "Citrus clementina",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "2-4 מטר",
    bloomSeason: "אביב",
    description: "כלאיים של מנדרינה ותפוז עם פרי מתוק ותכלתי. עץ גינה קומפקטי.",
    tips: "יבול מוקדם — מוכן לקטיף בנובמבר-דצמבר.",
  },
  {
    id: 23,
    nameHe: "לימונית",
    nameLatin: "Citrus hystrix",
    categories: ["citrus"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "אביב",
    description: "הדר דקורטיבי בעל עלים כפולים ייחודיים. הפרי עשיר בארומה.",
    tips: "מתאים לגידול בעציץ ולבישול אסייתי.",
  },
  // ---- עצי נוי ----
  {
    id: 24,
    nameHe: "ג'קרנדה",
    nameLatin: "Jacaranda mimosifolia",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "8-15 מטר",
    bloomSeason: "אביב-קיץ",
    description: "עץ נוי מרהיב עם אשכולות פרחים סגולים. עץ ציון מרכזי ברחובות ישראל.",
    tips: "אינו אוהב קרה — שתול באזורים חמים.",
  },
  {
    id: 25,
    nameHe: "בוגנוויליה",
    nameLatin: "Bougainvillea spectabilis",
    categories: ["ornamental-trees", "shrubs", "climbers"],
    sun: "full",
    water: "low",
    height: "3-10 מטר",
    bloomSeason: "כל השנה",
    description: "שיח/מטפס מרהיב עם עלי מכסה צבעוניים (ורוד, כתום, לבן). פורח כמעט כל השנה.",
    tips: "פחות מים = יותר פרחים. גזום אחרי כל גל פריחה.",
  },
  {
    id: 26,
    nameHe: "קסיה",
    nameLatin: "Cassia spectabilis",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "5-10 מטר",
    bloomSeason: "סתיו-חורף",
    description: "עץ נוי עם אשכולות פרחים צהובים בולטים בחורף.",
    tips: "פורח בעת שרוב העצים ישנים — מעניק צבע לגינת החורף.",
  },
  {
    id: 27,
    nameHe: "טיפואנה",
    nameLatin: "Tipuana tipu",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "10-20 מטר",
    bloomSeason: "קיץ",
    description: "עץ נוי גדול עם פרחים צהובים-כתומים ועלים עדינים. נותן צל נרחב.",
    tips: "עץ גדל מהיר — תכנן שטח מספיק לגדילתו.",
  },
  {
    id: 28,
    nameHe: "פלמת מלכה",
    nameLatin: "Syagrus romanzoffiana",
    categories: ["ornamental-trees", "trees"],
    sun: "full",
    water: "medium",
    height: "8-15 מטר",
    bloomSeason: "קיץ",
    description: "דקל נוי מרשים עם כתר ירוק טבעי. מתאים לפינות גן ולשדרות.",
    tips: "צריך דשן מיוחד לדקלים לשמירה על עלים ירוקים.",
  },
  {
    id: 29,
    nameHe: "ואשינגטוניה",
    nameLatin: "Washingtonia robusta",
    categories: ["ornamental-trees", "trees"],
    sun: "full",
    water: "low",
    height: "15-25 מטר",
    bloomSeason: "קיץ",
    description: "דקל גבוה ורזה עם חצאית של עלים יבשים. נפוץ מאוד ברחובות ישראל.",
    tips: "עמיד מאוד — כמעט אינו דורש טיפול לאחר ביסוס.",
  },
  {
    id: 30,
    nameHe: "פיקוס בנגלנסיס",
    nameLatin: "Ficus benghalensis",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "15-25 מטר",
    bloomSeason: "קיץ",
    description: "עץ ענק עם שורשי אוויר יורדים. מעניק צל נרחב.",
    tips: "שורשים פולשניים — שתול רחוק ממבנים וצנרת.",
  },
  {
    id: 31,
    nameHe: "שיטה כחלחלה",
    nameLatin: "Acacia saligna",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "low",
    height: "3-8 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח/עץ קטן עם כדורים צהובים ריחניים בחורף. עמיד בצורת.",
    tips: "גדל מהיר ומתאים לגידור ולייצוב קרקע.",
  },
  {
    id: 32,
    nameHe: "אלבציה",
    nameLatin: "Albizia julibrissin",
    categories: ["ornamental-trees"],
    sun: "full",
    water: "medium",
    height: "6-12 מטר",
    bloomSeason: "קיץ",
    description: "עץ נוי עם פרחים ורודים כמו ראשי סיכות. עלים עדינים מתקפלים בלילה.",
    tips: "מתאים לגינה אסייתית — עלים עדינים ופרחים קסומים.",
  },
  // ---- עצים ----
  {
    id: 33,
    nameHe: "ברוש",
    nameLatin: "Cupressus sempervirens",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "15-25 מטר",
    description: "עץ ירוק-עד צר ומוארך האייקוני של הנוף הים-תיכוני. עמיד לחום ולצורת.",
    tips: "שתול בשורות ליצירת מסך רוח ופרטיות.",
  },
  {
    id: 34,
    nameHe: "אורן ירושלים",
    nameLatin: "Pinus halepensis",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "10-20 מטר",
    bloomSeason: "אביב",
    description: "עץ מחטני ים-תיכוני עמיד בחום ובצורת. מאפיין את נוף ההרים בישראל.",
    tips: "ביוש ביסוס ראשוני — לאחר מכן כמעט אינו צריך השקיה.",
  },
  {
    id: 35,
    nameHe: "אקליפטוס",
    nameLatin: "Eucalyptus camaldulensis",
    categories: ["trees"],
    sun: "full",
    water: "medium",
    height: "15-30 מטר",
    description: "עץ אוסטרלי גדל-מהיר עם עלים בריחניים. עמיד לחום ולחיות מים.",
    tips: "שורשים עמוקים ומרחיקים — שמור מרחק ממבנים.",
  },
  {
    id: 36,
    nameHe: "ג'ינקו",
    nameLatin: "Ginkgo biloba",
    categories: ["trees"],
    sun: "full",
    water: "medium",
    height: "15-25 מטר",
    bloomSeason: "אביב",
    description: "עץ עתיק יומין - 'מאובן חי'. עלים ייחודיים בצורת מניפה צהובים בסתיו.",
    tips: "בחר עצים זכרים בלבד — פרי הנקבה בעל ריח חזק.",
  },
  {
    id: 37,
    nameHe: "ערבה בוכייה",
    nameLatin: "Salix babylonica",
    categories: ["trees"],
    sun: "full",
    water: "high",
    height: "8-15 מטר",
    description: "עץ עם ענפים תלויים רומנטיים. אוהב מים — מושלם ליד בריכות ואגמים.",
    tips: "שתול רחוק מצנרת — שורשיו מחפשים מים בנמרצות.",
  },
  {
    id: 38,
    nameHe: "חרוב",
    nameLatin: "Ceratonia siliqua",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "5-10 מטר",
    description: "עץ ים-תיכוני ירוק-עד עמיד מאוד. קרוביו מניבים תרמילים מתוקים.",
    tips: "עמיד בצורת ובחום — מתאים לגינה ים-תיכונית.",
  },
  {
    id: 39,
    nameHe: "שקמה",
    nameLatin: "Ficus sycomorus",
    categories: ["trees"],
    sun: "full",
    water: "medium",
    height: "10-20 מטר",
    description: "עץ תנ\"כי ירוק-עד עם גזע מרשים וצל נרחב. מוזכר בכתבי הקודש.",
    tips: "עץ גדול מאוד — מתאים לשטחים גדולים בלבד.",
  },
  {
    id: 40,
    nameHe: "אשל",
    nameLatin: "Tamarix aphylla",
    categories: ["trees"],
    sun: "full",
    water: "low",
    height: "5-10 מטר",
    description: "עץ חסין בצורה ומליחות. פרחים ורודים עדינים ועלים כחלחלים.",
    tips: "אחד העצים העמידים ביותר לתנאי מדבר ואדמה מלוחה.",
  },
  // ---- שיחים ----
  {
    id: 41,
    nameHe: "ורד",
    nameLatin: "Rosa × hybrida",
    categories: ["shrubs"],
    sun: "full",
    water: "medium",
    height: "0.5-2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "שיח הפרח הקלאסי והאהוב ביותר. מגוון אינסופי של צבעים וצורות.",
    tips: "גזום בסוף החורף והדש בסידן וזרחן לפריחה מרשימה.",
  },
  {
    id: 42,
    nameHe: "הביסקוס",
    nameLatin: "Hibiscus rosa-sinensis",
    categories: ["shrubs"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "כל השנה",
    description: "שיח טרופי עם פרחים ענקיים צבעוניים. פורח כמעט כל השנה בסביבה חמה.",
    tips: "גזום בין עונות לשמירת צורה קומפקטית ופריחה מרובה.",
  },
  {
    id: 43,
    nameHe: "פלומריה",
    nameLatin: "Plumeria rubra",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "2-5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח/עץ קטן עם פרחים ריחניים מרהיבים. מסמל את ההוואי וחיי הטרופיים.",
    tips: "עמיד לצורת — מחרוזות פרחים לריח שכיח בגינות טרופיות.",
  },
  {
    id: 44,
    nameHe: "נריום",
    nameLatin: "Nerium oleander",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "2-4 מטר",
    bloomSeason: "קיץ",
    description: "שיח עמיד בצורה עם פרחים ורודים/לבנים/אדומים. זהירות - רעיל מאוד.",
    tips: "אל תשרוף ענפים — עשן גם הוא רעיל.",
  },
  {
    id: 45,
    nameHe: "לבנדר",
    nameLatin: "Lavandula angustifolia",
    categories: ["shrubs", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח ריחני כחלכחל-סגול. מושך פרפרים ודבורים, דוחה מזיקים.",
    tips: "גזום שליש מהצמח אחרי הפריחה לשמירה על צורה קומפקטית.",
  },
  {
    id: 46,
    nameHe: "רוזמרין",
    nameLatin: "Rosmarinus officinalis",
    categories: ["shrubs", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-1.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח ארומטי ים-תיכוני עם עלים עדינים ופרחים כחולים. בישול ונוי כאחד.",
    tips: "ניקוז טוב חיוני — שורשי ריקבון ממים עומדים.",
  },
  {
    id: 47,
    nameHe: "פלומבגו",
    nameLatin: "Plumbago auriculata",
    categories: ["shrubs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח עם פרחים תכולים-שמיים מרהיבים. פורח ממושך ואוהב חום.",
    tips: "גזום בסוף החורף לצמיחה רעננה ופריחה מרשימה.",
  },
  {
    id: 48,
    nameHe: "אדניום",
    nameLatin: "Adenium obesum",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "0.5-2 מטר",
    bloomSeason: "קיץ",
    description: "שיח סוקולנטי עם גזע תפוח ופרחים ורודים/אדומים. מוכר כ'ורד המדבר'.",
    tips: "לא להשקות בחורף — הצמח נמצא בשינה.",
  },
  {
    id: 49,
    nameHe: "יסמין ערבי",
    nameLatin: "Jasminum sambac",
    categories: ["shrubs", "climbers"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "שיח/מטפס עם פרחים לבנים ריחניים מאוד. ריח אינטנסיבי בקיץ.",
    tips: "הסיר פרחים קמלים לעידוד פריחה מתמשכת.",
  },
  {
    id: 50,
    nameHe: "גרניום",
    nameLatin: "Pelargonium × hortorum",
    categories: ["shrubs", "perennials"],
    sun: "full",
    water: "medium",
    height: "0.3-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "שיח פורח ועמיד עם עלים ריחניים. מגוון רחב של צבעים ומתאים לעציצים.",
    tips: "הסר עלים וגבעולים יבשים לפריחה מתמשכת.",
  },
  {
    id: 51,
    nameHe: "דורמנה",
    nameLatin: "Teucrium fruticans",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח ים-תיכוני עם עלים כסופים ופרחים כחולים. עמיד לחום ולצורת.",
    tips: "גזום לאחר הפריחה לשמירת צורה קומפקטית.",
  },
  {
    id: 52,
    nameHe: "מירטוס",
    nameLatin: "Myrtus communis",
    categories: ["shrubs"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "שיח ים-תיכוני ריחני עם פרחים לבנים קטנים ועלים מבריקים.",
    tips: "מתאים לגידור ולעיצוב טופיאר — מקבל גיזום היטב.",
  },
  // ---- שיחי הסתרה ----
  {
    id: 53,
    nameHe: "פיטוספורום",
    nameLatin: "Pittosporum tobira",
    categories: ["privacy-shrubs"],
    sun: "partial",
    water: "low",
    height: "1-4 מטר",
    bloomSeason: "אביב",
    description: "שיח הסתרה עמיד עם עלים מבריקים ופרחים ריחניים לבנים. עמיד לצל.",
    tips: "גדר עמידה ומצוינת — כמעט אינה צריכה טיפול.",
  },
  {
    id: 54,
    nameHe: "ליגוסטרום",
    nameLatin: "Ligustrum japonicum",
    categories: ["privacy-shrubs"],
    sun: "partial",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "קיץ",
    description: "שיח הסתרה עם עלים מבריקים ופרחים לבנים ריחניים. גדל מהיר ועמיד.",
    tips: "גזם 2-3 פעמים בשנה לגדר צפופה ומסודרת.",
  },
  {
    id: 55,
    nameHe: "פוטיניה",
    nameLatin: "Photinia × fraseri",
    categories: ["privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "אביב",
    description: "שיח הסתרה עם עלים חדשים בצבע אדום בולט. יוצר גדר ירוקה צפופה.",
    tips: "העלים החדשים אדומים — גזום לעידוד צמיחה צבעונית.",
  },
  {
    id: 56,
    nameHe: "וויבורנום",
    nameLatin: "Viburnum odoratissimum",
    categories: ["privacy-shrubs"],
    sun: "partial",
    water: "medium",
    height: "2-5 מטר",
    bloomSeason: "אביב",
    description: "שיח הסתרה עם עלים ירוקים מבריקים ופרחים לבנים ריחניים. גדל מהיר.",
    tips: "אחד הגדרות הריחניות ביותר — מושלם ליד פתחי בית.",
  },
  {
    id: 57,
    nameHe: "ספרינה",
    nameLatin: "Escallonia rubra",
    categories: ["privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח הסתרה עם פרחים ורודים-אדומים קטנים. עמיד לרוח ולמלח.",
    tips: "מתאים לאזורי חוף — עמיד לרוח ים מלוחה.",
  },
  {
    id: 58,
    nameHe: "אבליה",
    nameLatin: "Abelia × grandiflora",
    categories: ["privacy-shrubs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "שיח מטה גמיש עם פרחים לבנים קטנים. פורח ממושך ומושך פרפרים.",
    tips: "גזום קלות לשמירת צורה — אינו אוהב גיזום נמרץ.",
  },
  {
    id: 59,
    nameHe: "דפנה",
    nameLatin: "Viburnum tinus",
    categories: ["privacy-shrubs", "shade"],
    sun: "partial",
    water: "low",
    height: "2-4 מטר",
    bloomSeason: "חורף-אביב",
    description: "שיח הסתרה ירוק-עד הסובל צל. פורח בחורף בפרחים לבנים ורוד.",
    tips: "אחד מהשיחים הטובים ביותר לצל — עמיד ויפה.",
  },
  {
    id: 60,
    nameHe: "לנטנה",
    nameLatin: "Lantana camara",
    categories: ["shrubs", "privacy-shrubs", "perennials"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "כל השנה",
    description: "שיח צבעוני עם פרחים המחליפים צבע — צהוב, כתום, ורוד. פורח כל השנה.",
    tips: "עמיד בצורת ומושך פרפרים — אידיאלי לגינת פרפרים.",
  },
  // ---- רב שנתיים ----
  {
    id: 61,
    nameHe: "סטרליציה",
    nameLatin: "Strelitzia reginae",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "1-1.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח ייחודי בצורת ראש ציפור טרופי. אחד הפרחים המרשימים ביותר לגינה.",
    tips: "דרוש אור מלא ואדמה ניקוזית להבטחת פריחה.",
  },
  {
    id: 62,
    nameHe: "אגפנטוס",
    nameLatin: "Agapanthus africanus",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח פורח עם אשכולות פרחים כחולים/לבנים על גבעולים ארוכים. עמיד.",
    tips: "משגשג כשמוצף שמש — כמות גבוהה של פרחים בצפיפות.",
  },
  {
    id: 63,
    nameHe: "קנה פרח",
    nameLatin: "Canna indica",
    categories: ["perennials", "geophytes"],
    sun: "full",
    water: "high",
    height: "1-2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "צמח טרופי עם עלים גדולים ופרחים ורודים/כתומים/אדומים. מרשים ובולט.",
    tips: "אוהב מים — השקה שוטפת בקיץ חיונית.",
  },
  {
    id: 64,
    nameHe: "אכינצאה",
    nameLatin: "Echinacea purpurea",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח מרפא ונוי עם פרחים סגולים עם מרכז קוני. מושך חרקים מועילים.",
    tips: "השאר ראשי פרחים יבשים לחורף — ציפורים אוהבות את הזרעים.",
  },
  {
    id: 65,
    nameHe: "רודבקיה",
    nameLatin: "Rudbeckia hirta",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.5-1 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח שמשי צהוב עם מרכז חום כהה. עמיד ופורח ממושך.",
    tips: "גזם פרחים קמלים להארכת עונת הפריחה.",
  },
  {
    id: 66,
    nameHe: "אסטרומריה",
    nameLatin: "Alstroemeria",
    categories: ["perennials"],
    sun: "partial",
    water: "medium",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "פרח כרוך בצבעים מרהיבים — ורוד, כתום, לבן עם פסים. מתאים לאגרטלים.",
    tips: "עמיד בקטיף — נמשך שבועות באגרטל.",
  },
  {
    id: 67,
    nameHe: "גזניה",
    nameLatin: "Gazania rigens",
    categories: ["perennials"],
    sun: "full",
    water: "low",
    height: "0.2-0.4 מטר",
    bloomSeason: "אביב-סתיו",
    description: "פרח אפריקאי צבעוני הפותח בשמש וסוגר בצל. עמיד בצורת.",
    tips: "מצוין לכיסוי קרקע במדרונות — עמיד ומרהיב.",
  },
  {
    id: 68,
    nameHe: "דיאנתוס",
    nameLatin: "Dianthus caryophyllus",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.3-1 מטר",
    bloomSeason: "אביב-סתיו",
    description: "ציפורן ריחני בצבעים מגוונים — ורוד, אדום, לבן. מתאים לאגרטלים.",
    tips: "גזום לאחר הפריחה לגל פריחה נוסף.",
  },
  {
    id: 69,
    nameHe: "ליאטריס",
    nameLatin: "Liatris spicata",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.4-1 מטר",
    bloomSeason: "קיץ",
    description: "צמח שיבולת עם פרחים סגולים-ורודים פותחים מלמעלה למטה. ייחודי.",
    tips: "מצוין לגינת פרפרים — נמשך היטב כפרח חתוך.",
  },
  {
    id: 70,
    nameHe: "פנסטמון",
    nameLatin: "Penstemon digitalis",
    categories: ["perennials"],
    sun: "full",
    water: "medium",
    height: "0.5-1 מטר",
    bloomSeason: "אביב-קיץ",
    description: "צמח נוי אמריקאי עם פרחים כמו פעמוניות לבנות-ורודות. מושך יונקים.",
    tips: "עמיד בצורת — מצוין לגינה אמריקאית.",
  },
  {
    id: 71,
    nameHe: "סיגל",
    nameLatin: "Viola odorata",
    categories: ["perennials", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.2 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח קטן וריחני עם עלים לבביים. גדל בצל ופורח בחורף ובאביב.",
    tips: "מתאים לכיסוי קרקע תחת עצים — אוהב צל קליל.",
  },
  {
    id: 72,
    nameHe: "עקיזה",
    nameLatin: "Achillea millefolium",
    categories: ["perennials"],
    sun: "full",
    water: "low",
    height: "0.4-0.8 מטר",
    bloomSeason: "קיץ",
    description: "צמח מרפא ונוי עם פרחים שטוחים בצבעים שונים. עמיד בצורת ובחום.",
    tips: "יבש היטב כפרח חתוך לשמירת צבע.",
  },
  {
    id: 73,
    nameHe: "סגה",
    nameLatin: "Salvia officinalis",
    categories: ["perennials", "herbs"],
    sun: "full",
    water: "low",
    height: "0.5-0.8 מטר",
    bloomSeason: "אביב-קיץ",
    description: "שיח ריחני ים-תיכוני בעל עלים כסופים ופרחים כחולים. מרפא ותבלין.",
    tips: "גזום לאחר הפריחה לשמירת עלים ריחניים ורעננים.",
  },
  // ---- עונתיים ----
  {
    id: 74,
    nameHe: "פטוניה",
    nameLatin: "Petunia × hybrida",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "פרח עונתי צבעוני מאוד עם מגוון אינסופי של גוונים. מתאים לעציצים ולתלויים.",
    tips: "גזום קלות אחת לשבועיים להמשך פריחה שופעת.",
  },
  {
    id: 75,
    nameHe: "חמניות",
    nameLatin: "Helianthus annuus",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "1-3 מטר",
    bloomSeason: "קיץ",
    description: "פרח השמש הסובב פנים לכיוון האור. פרחים ענקיים צהובים. עגב ה-שמחה.",
    tips: "זרע ישירות בשטח — אינה אוהבת השתלה.",
  },
  {
    id: 76,
    nameHe: "ציניה",
    nameLatin: "Zinnia elegans",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "0.3-0.9 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח עונתי צבעוני מאוד עמיד לחום. פריחה ממושכת מקיץ עד סתיו.",
    tips: "גזום פרחים קמלים להארכת עונת הפריחה.",
  },
  {
    id: 77,
    nameHe: "קוסמוס",
    nameLatin: "Cosmos bipinnatus",
    categories: ["annuals"],
    sun: "full",
    water: "low",
    height: "0.6-1.2 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח גבוה ועדין עם עלים דמויי נוצות ופרחים ורודים/לבנים/סגולים.",
    tips: "עמיד בצורת — אחד מהפרחים הקלים ביותר לגידול.",
  },
  {
    id: 78,
    nameHe: "טגטס",
    nameLatin: "Tagetes patula",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "ציפורן אפריקאית עם פרחים כתומים-צהובים. דוחה מזיקים מהגינה.",
    tips: "שתול בגינת ירקות לדחיית נמטודות ומזיקים.",
  },
  {
    id: 79,
    nameHe: "אנמונה",
    nameLatin: "Anemone coronaria",
    categories: ["annuals", "geophytes"],
    sun: "full",
    water: "medium",
    height: "0.2-0.4 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח בר ישראלי מוכר בצבעים אדום, לבן, סגול. פורח בשדות בחורף.",
    tips: "שתול כפקעות בסתיו לפריחה בחורף-אביב.",
  },
  {
    id: 80,
    nameHe: "פרג",
    nameLatin: "Papaver rhoeas",
    categories: ["annuals"],
    sun: "full",
    water: "low",
    height: "0.3-0.9 מטר",
    bloomSeason: "אביב",
    description: "פרח בר ישראלי אדום-לוהט הפורח בשדות בסוף החורף. עדין ויפהפה.",
    tips: "פזר זרעים בסתיו לפריחה ספונטנית באביב.",
  },
  {
    id: 81,
    nameHe: "נסטורציום",
    nameLatin: "Tropaeolum majus",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.3-3 מטר",
    bloomSeason: "קיץ",
    description: "פרח אכיל עם פרחים כתומים-צהובים. העלים, הפרחים וזרעי הקפרס אכילים.",
    tips: "פרח ועלים אכילים — מצוין לסלטים.",
  },
  {
    id: 82,
    nameHe: "ארנבנית",
    nameLatin: "Antirrhinum majus",
    categories: ["annuals"],
    sun: "full",
    water: "medium",
    height: "0.3-0.8 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח בצורת פרפר עם שפתיים הנסגרות. מגוון צבעים ורצועות.",
    tips: "שתול בסתיו לפריחה עשירה בחורף ובאביב.",
  },
  {
    id: 83,
    nameHe: "לוביליה",
    nameLatin: "Lobelia erinus",
    categories: ["annuals", "trailing"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב-סתיו",
    description: "צמח נשפך קטן עם פרחים כחולים/לבנים עדינים. מצוין לתלויים ולשוליים.",
    tips: "גזום לאחר הפריחה הראשונה לגל פריחה נוסף.",
  },
  {
    id: 84,
    nameHe: "קליברכואה",
    nameLatin: "Calibrachoa",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.1-0.3 מטר",
    bloomSeason: "כל השנה",
    description: "פטוניה מיניאטורית עם אלפי פרחים קטנטנים. מצוין לסלי תלייה ועציצים.",
    tips: "לא צריך להסיר פרחים קמלים — פורח מעצמו.",
  },
  {
    id: 85,
    nameHe: "ורבנה",
    nameLatin: "Verbena × hybrida",
    categories: ["annuals", "trailing"],
    sun: "full",
    water: "medium",
    height: "0.2-0.5 מטר",
    bloomSeason: "אביב-סתיו",
    description: "צמח נשפך ופורח בצבעים מגוונים. מצוין לכיסוי קרקע ולתלויים.",
    tips: "גזום קלות להמשך פריחה צפופה.",
  },
  // ---- צמחיה לבית ----
  {
    id: 86,
    nameHe: "מונסטרה",
    nameLatin: "Monstera deliciosa",
    categories: ["indoor"],
    sun: "shade",
    water: "medium",
    height: "1-5 מטר",
    description: "צמח בית אייקוני עם עלים גדולים מחוררים. סמל לעיצוב טרופי מודרני.",
    tips: "נגב עלים בלחית לניקוי ולשמירת ברק.",
  },
  {
    id: 87,
    nameHe: "פוטוס",
    nameLatin: "Epipremnum aureum",
    categories: ["indoor", "trailing"],
    sun: "shade",
    water: "medium",
    height: "מטפס",
    description: "צמח בית עמיד ביותר עם עלים לבביים ירוקים-צהובים. כמעט אי-אפשר להרוג.",
    tips: "מנקה אוויר — מצוין לשטחים פנים ללא אור טבעי.",
  },
  {
    id: 88,
    nameHe: "סנסוויריה",
    nameLatin: "Sansevieria trifasciata",
    categories: ["indoor"],
    sun: "partial",
    water: "low",
    height: "0.3-1.2 מטר",
    description: "צמח בית עמיד ביותר עם עלים חרביים ישרים. מנקה אוויר ועמיד בהזנחה.",
    tips: "לא להשקות יתר — שורש ריקבון הוא הסכנה היחידה.",
  },
  {
    id: 89,
    nameHe: "פילודנדרון",
    nameLatin: "Philodendron hederaceum",
    categories: ["indoor", "trailing"],
    sun: "shade",
    water: "medium",
    height: "0.5-3 מטר",
    description: "צמח בית נשפך עם עלים לבביים ירוקים. גדל מהיר ועמיד לתנאים שונים.",
    tips: "הסר עלים צהובים מיד — סימן להשקיה יתר.",
  },
  {
    id: 90,
    nameHe: "פיקוס בנג'מין",
    nameLatin: "Ficus benjamina",
    categories: ["indoor"],
    sun: "partial",
    water: "medium",
    height: "1-3 מטר (בבית)",
    description: "עץ בית קלאסי עם עלים קטנים מבריקים. מרשים ומנקה אוויר.",
    tips: "אל תזיז לעתים קרובות — מגיב בנשירת עלים לשינויי מיקום.",
  },
  {
    id: 91,
    nameHe: "קלתיאה",
    nameLatin: "Calathea orbifolia",
    categories: ["indoor"],
    sun: "shade",
    water: "high",
    height: "0.5-0.9 מטר",
    description: "צמח בית מפואר עם עלים מפוספסים כסוף-ירוק. עלים נסגרים בלילה.",
    tips: "השתמש במי גשמים או מי שתייה — רגיש לכלור.",
  },
  {
    id: 92,
    nameHe: "ספאתיפילום",
    nameLatin: "Spathiphyllum wallisii",
    categories: ["indoor"],
    sun: "shade",
    water: "medium",
    height: "0.4-0.8 מטר",
    bloomSeason: "קיץ",
    description: "צמח בית עם פרחים לבנים אלגנטיים ועלים כהים ומבריקים. מנקה אוויר.",
    tips: "מאותת צמא בשמלת עלים — השקה מיידית תחזיר אותו.",
  },
  {
    id: 93,
    nameHe: "דרקנה",
    nameLatin: "Dracaena fragrans",
    categories: ["indoor"],
    sun: "partial",
    water: "low",
    height: "1-2 מטר (בבית)",
    description: "צמח בית גבוה עם עלים פסים רחבים. סובל תנאי אור שונים ומנקה אוויר.",
    tips: "קצות עלים חומים מסמנים מים קשים — עבור למי גשמים.",
  },
  {
    id: 94,
    nameHe: "פלמת ארקה",
    nameLatin: "Dypsis lutescens",
    categories: ["indoor", "ornamental-trees"],
    sun: "partial",
    water: "medium",
    height: "1-2 מטר (בבית)",
    description: "דקל בית אלגנטי עם גזעים צהבהבים ועלים ארוכים. מעניק אווירה טרופית.",
    tips: "אחד ממנקי האוויר הטובים ביותר — לפי נאסא.",
  },
  {
    id: 95,
    nameHe: "אנתוריום",
    nameLatin: "Anthurium andraeanum",
    categories: ["indoor"],
    sun: "shade",
    water: "medium",
    height: "0.4-0.8 מטר",
    bloomSeason: "כל השנה",
    description: "צמח בית עם פרחים לב-אדומים מבריקים. פורח כמעט כל השנה.",
    tips: "הגן מפני אור שמש ישיר — שורף את העלים.",
  },
  {
    id: 96,
    nameHe: "פיקוס ליראטה",
    nameLatin: "Ficus lyrata",
    categories: ["indoor"],
    sun: "partial",
    water: "medium",
    height: "1-2 מטר (בבית)",
    description: "עץ בית מודרני עם עלים ענקיים בצורת כינור. טרנד עיצוב פנים מרכזי.",
    tips: "ניגב עלים בלחות ותן אור מספיק — גדל לאט.",
  },
  {
    id: 97,
    nameHe: "זמיוקולקס",
    nameLatin: "Zamioculcas zamiifolia",
    categories: ["indoor"],
    sun: "shade",
    water: "low",
    height: "0.5-1 מטר",
    description: "צמח בית עמיד מאוד עם עלים מבריקים כהים. כמעט בלתי ניתן להרוג.",
    tips: "שוכח השקיה חודשים? לא נורא — ZZ מחכה בסבלנות.",
  },
  {
    id: 98,
    nameHe: "אספידיסטרה",
    nameLatin: "Aspidistra elatior",
    categories: ["indoor", "shade"],
    sun: "shade",
    water: "low",
    height: "0.5-0.8 מטר",
    description: "צמח עמיד ביותר עם עלים כהים ורחבים. מכונה 'צמח הברזל' בשל עמידותו.",
    tips: "מתאים לפינות חשוכות שאף צמח אחר לא שורד בהן.",
  },
  // ---- סוקולנטים ----
  {
    id: 99,
    nameHe: "אלוורה",
    nameLatin: "Aloe vera",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "סוקולנט מרפא מפורסם עם עלים בשרניים מלאי ג'ל מרגיע לעור.",
    tips: "שבור עלה ישן ל כוויות ועקיצות — ג'ל הוא תרופת טבע.",
  },
  {
    id: 100,
    nameHe: "קרסולה",
    nameLatin: "Crassula ovata",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.5-1.5 מטר",
    bloomSeason: "חורף",
    description: "סוקולנט עמיד עם עלים עגולים ומבריקים. מכונה 'עץ הזהב' ומסמל מזל.",
    tips: "כמעט אינו מת — אחד הסוקולנטים הקלים לגידול.",
  },
  {
    id: 101,
    nameHe: "אכאוריה",
    nameLatin: "Echeveria elegans",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב",
    description: "סוקולנט ורדי מרהיב בצורת ורד. עלים עבים כסופים-כחלחלים.",
    tips: "הרחק ממים מלמעלה — מים בין העלים גורמים לריקבון.",
  },
  {
    id: 102,
    nameHe: "סדום",
    nameLatin: "Sedum rubrotinctum",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "חורף",
    description: "סוקולנט עם עלים עגולים-בשרניים בצבע ירוק-אדום. מכונה 'ג'לי-בינס'.",
    tips: "אדום יותר בשמש — ירוק בצל. אחד הפשוטים לרבייה.",
  },
  {
    id: 103,
    nameHe: "הוורתיה",
    nameLatin: "Haworthia attenuata",
    categories: ["succulents", "indoor"],
    sun: "partial",
    water: "low",
    height: "0.1-0.2 מטר",
    description: "סוקולנט קטן עם פסים לבנים על עלים ירוקים. סובל צל טוב יותר מרוב הסוקולנטים.",
    tips: "אחד הסוקולנטים המעטים המתאימים לחלון צפוני.",
  },
  {
    id: 104,
    nameHe: "קלנחואה",
    nameLatin: "Kalanchoe blossfeldiana",
    categories: ["succulents", "indoor"],
    sun: "full",
    water: "low",
    height: "0.2-0.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "סוקולנט פורח עם פרחים קטנים-בולטים בכתום, צהוב, ורוד, אדום.",
    tips: "לאחר הפריחה: גזום, הפחת מים והפרח שוב.",
  },
  {
    id: 105,
    nameHe: "אגבה",
    nameLatin: "Agave americana",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "1-2 מטר",
    bloomSeason: "פעם בחיים",
    description: "סוקולנט ענק עם עלים שנוניים כחולים-אפורים. פורח פעם אחת בחייו.",
    tips: "זהירות מקצוות חדות — מתאים לגינה רשמית ובולטת.",
  },
  {
    id: 106,
    nameHe: "אלו ארבורסנס",
    nameLatin: "Aloe arborescens",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "1-3 מטר",
    bloomSeason: "חורף",
    description: "אלוורה גדולה עם פרחים כתומים-אדומים בחורף. עמידה מאוד ויפה.",
    tips: "פורח בחורף כשרוב הגינה ישנה — ספק צבע לעונה הקרה.",
  },
  {
    id: 107,
    nameHe: "גרפטופטלום",
    nameLatin: "Graptopetalum paraguayense",
    categories: ["succulents"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    description: "סוקולנט ורדי קטן עם עלים ורודים-סגולים. קל לרבייה מעלים בודדים.",
    tips: "נפרד עלה מהגבעול, הנח על אדמה — שורש לבד.",
  },
  {
    id: 108,
    nameHe: "פורסלאן",
    nameLatin: "Portulaca grandiflora",
    categories: ["succulents", "annuals", "trailing"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "קיץ",
    description: "צמח נשפך עם פרחים ורדיים-ססגוניים הנפתחים בשמש. עמיד לחום.",
    tips: "פותח בשמש וסוגר בצל — מרביץ תצוגה ביום בלבד.",
  },
  // ---- קקטוסים ----
  {
    id: 109,
    nameHe: "צבר",
    nameLatin: "Opuntia ficus-indica",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "1-5 מטר",
    bloomSeason: "אביב-קיץ",
    description: "קקטוס ישראלי אייקוני עם פרי אכיל (תאנת-הודיה). נותן גדר עמידה.",
    tips: "פרי אכיל — השתמש בכפפות עבות לקטיף.",
  },
  {
    id: 110,
    nameHe: "קרקטוס",
    nameLatin: "Cereus peruvianus",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "2-6 מטר",
    bloomSeason: "לילה",
    description: "קקטוס עמודי גבוה ומרשים. פורח בלילה בפרחים גדולים לבנים.",
    tips: "אחד הקקטוסים הגבוהים ביותר — מרשים כנקודת מוקד בגינה.",
  },
  {
    id: 111,
    nameHe: "פרחינוקקטוס",
    nameLatin: "Ferocactus cylindraceus",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "0.3-1 מטר",
    bloomSeason: "אביב",
    description: "קקטוס גלילי עם קוצים צבעוניים חזקים. נקרא 'חבית קקטוס'.",
    tips: "לא להשקות בחורף בכלל — רגיש לריקבון בקור.",
  },
  {
    id: 112,
    nameHe: "ממילריה",
    nameLatin: "Mammillaria elongata",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "אביב",
    description: "קקטוס קטן-עגלגל עם קוצים דקים זהובים. מניב שכים צהובים קטנטנים.",
    tips: "קל לגידול בעציץ — אידיאלי לאוספי קקטוסים.",
  },
  {
    id: 113,
    nameHe: "איצ'ינוקצ'טוס",
    nameLatin: "Echinocactus grusonii",
    categories: ["cacti"],
    sun: "full",
    water: "low",
    height: "0.3-0.8 מטר",
    description: "קקטוס ענק כדורי עם קוצים צהובים. מכונה 'כיסא החמות'. גדל לאט.",
    tips: "גדל לאט מאוד — קקטוס גדול הוא בן עשרות שנים.",
  },
  // ---- גיאופיטים ----
  {
    id: 114,
    nameHe: "צבעוני",
    nameLatin: "Tulipa gesneriana",
    categories: ["geophytes"],
    sun: "full",
    water: "medium",
    height: "0.2-0.6 מטר",
    bloomSeason: "אביב",
    description: "פרח אביב קלאסי בצבעים מרהיבים. מסמל את הופעת האביב בגינה.",
    tips: "שמור פקעות בקירור לפני שתילה — ישראל חמה מדי.",
  },
  {
    id: 115,
    nameHe: "נרקיס",
    nameLatin: "Narcissus tazetta",
    categories: ["geophytes"],
    sun: "full",
    water: "medium",
    height: "0.3-0.5 מטר",
    bloomSeason: "חורף-אביב",
    description: "פרח ריחני אהוב עם פרחים לבנים ומרכז צהוב. פורח בחורף-אביב.",
    tips: "שתול בסתיו — פרחים מרהיבים בפברואר-מרץ.",
  },
  {
    id: 116,
    nameHe: "רקפת",
    nameLatin: "Cyclamen persicum",
    categories: ["geophytes", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.1-0.3 מטר",
    bloomSeason: "חורף",
    description: "פרח חורפי עם פרחים ורודים-לבנים ועלים מנוקדים. פורח בצל.",
    tips: "השקה מלמטה בלבד — מים על הבצל גורמים לריקבון.",
  },
  {
    id: 117,
    nameHe: "גלדיולוס",
    nameLatin: "Gladiolus × hortulanus",
    categories: ["geophytes"],
    sun: "full",
    water: "medium",
    height: "0.6-1.2 מטר",
    bloomSeason: "קיץ",
    description: "פרח שיבולת גבוה עם פרחים צבעוניים גדולים לאורך הגבעול. לאגרטלים.",
    tips: "שתול פקעות בשלבים לפריחה מתמשכת לאורך הקיץ.",
  },
  {
    id: 118,
    nameHe: "אירוס",
    nameLatin: "Iris germanica",
    categories: ["geophytes"],
    sun: "full",
    water: "low",
    height: "0.3-1 מטר",
    bloomSeason: "אביב",
    description: "פרח אצילי עם עלים חרביים ופרחים מורכבים בסגול, לבן וכחול.",
    tips: "אל תשקה יתר — שורש עם ריקבון מסוכן.",
  },
  {
    id: 119,
    nameHe: "דהליה",
    nameLatin: "Dahlia pinnata",
    categories: ["geophytes"],
    sun: "full",
    water: "high",
    height: "0.3-1.5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "פרח מפואר עם פרחים ענקיים בצורות ובצבעים מגוונים. מלכת הגינה.",
    tips: "הוצא פקעות מהאדמה בחורף לשמירה עד השנה הבאה.",
  },
  {
    id: 120,
    nameHe: "חצב",
    nameLatin: "Urginea maritima",
    categories: ["geophytes"],
    sun: "full",
    water: "low",
    height: "0.3-1.5 מטר",
    bloomSeason: "סתיו",
    description: "צמח בר ישראלי עם שיבולת פרחים לבנה. פורח בסתיו לפני הצצת העלים.",
    tips: "פורח בלי עלים בסתיו — ייחודי ומרתק לגינה מדיטרנית.",
  },
  {
    id: 121,
    nameHe: "מוסקרי",
    nameLatin: "Muscari armeniacum",
    categories: ["geophytes"],
    sun: "full",
    water: "low",
    height: "0.1-0.2 מטר",
    bloomSeason: "אביב",
    description: "פרח קטן-כחול בצורת אשכול ענבים. מבשר האביב הראשון בגינה.",
    tips: "שתול בסתיו לפריחה מוקדמת ומרהיבה באביב.",
  },
  // ---- עשבי תיבול ----
  {
    id: 122,
    nameHe: "בזיליקום",
    nameLatin: "Ocimum basilicum",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול אהוב עם עלים ריחניים. חיוני לבישול איטלקי ומדיטרני.",
    tips: "גזם ראשי פרחים מיד — פריחה מחלישה את הארומה.",
  },
  {
    id: 123,
    nameHe: "נענע",
    nameLatin: "Mentha × piperita",
    categories: ["herbs"],
    sun: "partial",
    water: "high",
    height: "0.3-0.6 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול ריחני מאוד עם עלים מרעננים. מרחיב לכל הכיוונים.",
    tips: "שתול בעציץ — שורשים פולשניים כובשים את הגינה.",
  },
  {
    id: 124,
    nameHe: "תימין",
    nameLatin: "Thymus vulgaris",
    categories: ["herbs"],
    sun: "full",
    water: "low",
    height: "0.1-0.3 מטר",
    bloomSeason: "אביב-קיץ",
    description: "עשב ים-תיכוני קטן ריחני. עמיד בצורת ובחום — מתאים לגינה ים-תיכונית.",
    tips: "כיסוי קרקע נהדר בין אבנים — עמיד ודקורטיבי.",
  },
  {
    id: 125,
    nameHe: "אורגנו",
    nameLatin: "Origanum vulgare",
    categories: ["herbs"],
    sun: "full",
    water: "low",
    height: "0.2-0.6 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול ים-תיכוני חיוני לפיצה ולבישול ים-תיכוני. עמיד ועצמאי.",
    tips: "קטיף מגדיל ריכוז שמנים — גזם לעתים קרובות.",
  },
  {
    id: 126,
    nameHe: "כוסברה",
    nameLatin: "Coriandrum sativum",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "0.3-0.6 מטר",
    bloomSeason: "אביב",
    description: "עשב תיבול עם ניחוח חזק ומיוחד. חיוני לבישול מזרחי, תימני ואסייתי.",
    tips: "שתול בסביבה קרירה — פורח מהר בחום ומאבד טעם.",
  },
  {
    id: 127,
    nameHe: "פטרוזיליה",
    nameLatin: "Petroselinum crispum",
    categories: ["herbs"],
    sun: "partial",
    water: "medium",
    height: "0.2-0.5 מטר",
    description: "עשב תיבול מוכר ובסיסי לכל מטבח. עלים ירוקים עשירים בברזל.",
    tips: "גדל טוב גם בחצי-צל — מתאים לגינת מרפסת.",
  },
  {
    id: 128,
    nameHe: "שמיר",
    nameLatin: "Anethum graveolens",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "0.6-1 מטר",
    bloomSeason: "קיץ",
    description: "עשב תיבול גבוה עם עלים עדינים כנוצות. חיוני לבישול ישראלי.",
    tips: "זרע ישירות — אינו אוהב השתלה. שמר לחות.",
  },
  {
    id: 129,
    nameHe: "לואיזה",
    nameLatin: "Aloysia citrodora",
    categories: ["herbs"],
    sun: "full",
    water: "medium",
    height: "1-2 מטר",
    bloomSeason: "קיץ",
    description: "שיח תיבול עם ניחוח לימוני עז. מצוין להכנת תה ולשתייה קרה.",
    tips: "קצץ ל-צד ייבוש תה — טעמו משתפר עם הייבוש.",
  },
  {
    id: 130,
    nameHe: "מליסה",
    nameLatin: "Melissa officinalis",
    categories: ["herbs", "shade"],
    sun: "partial",
    water: "medium",
    height: "0.3-0.8 מטר",
    bloomSeason: "קיץ",
    description: "עשב לימוני מרגיע. מצוין לתה הרגעה וסובל קצת צל.",
    tips: "גזם לפני הפריחה לשמירת ריח לימון עז.",
  },
  // ---- מטפסים ----
  {
    id: 131,
    nameHe: "יסמין",
    nameLatin: "Jasminum polyanthum",
    categories: ["climbers"],
    sun: "partial",
    water: "medium",
    height: "מטפס 3-6 מטר",
    bloomSeason: "חורף-אביב",
    description: "מטפס ריחני עם פרחים לבנים-ורודים. הריח מילא לילות חורף ישראליים.",
    tips: "גזום לאחר הפריחה להכנה לגל הפריחה הבא.",
  },
  {
    id: 132,
    nameHe: "פסיפלורה",
    nameLatin: "Passiflora caerulea",
    categories: ["climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 5-10 מטר",
    bloomSeason: "קיץ",
    description: "מטפס עם פרחים מרהיבים ומורכבים בכחול-לבן. פרי אכיל קטן.",
    tips: "גדל מהיר מאוד — דרוש גידור חזק ורשת תמיכה.",
  },
  {
    id: 133,
    nameHe: "קפריפוליום",
    nameLatin: "Lonicera japonica",
    categories: ["climbers", "shade"],
    sun: "partial",
    water: "medium",
    height: "מטפס 4-10 מטר",
    bloomSeason: "קיץ",
    description: "מטפס ריחני עם פרחים צהובים-לבנים. עמיד בצל ובחום.",
    tips: "יכול לכסות גדר כולה — גדל מהיר בתנאים מגוונים.",
  },
  {
    id: 134,
    nameHe: "מנדוויליה",
    nameLatin: "Mandevilla sanderi",
    categories: ["climbers"],
    sun: "full",
    water: "medium",
    height: "מטפס 3-5 מטר",
    bloomSeason: "קיץ-סתיו",
    description: "מטפס טרופי עם פרחים ורודים-אדומים גדולים. מרשים על פרגולות וגדרות.",
    tips: "אינו עמיד לקרה — הכנס לבית בחורף.",
  },
  {
    id: 135,
    nameHe: "כרך",
    nameLatin: "Ipomoea purpurea",
    categories: ["climbers", "annuals"],
    sun: "full",
    water: "medium",
    height: "מטפס 3-5 מטר",
    bloomSeason: "קיץ",
    description: "מטפס שנתי מהיר עם פרחים סגולים-ורודים בצורת קול. כסוי מהיר.",
    tips: "גדל ב-6 שבועות מזרע — כיסוי מהיר ביותר לגינה.",
  },
];
